import {displayedShiftSpeed,storedShiftSpeed} from './car-speed.mjs';
import {parseTimeClipboard} from './time-input.mjs';
import {modCarBanks,modCarTargets,carModChanges} from './mod-car-targets.mjs';
import {bindingName} from './key-binding.mjs';
import {duplicatePackageIds,packageIdOf,requirementLabel,requirementNote,requirementStatus} from './mod-dependencies.mjs';
import {mountModelPreview} from './model-preview.js';
import {mountLogo} from './logo.js';
const $=s=>document.querySelector(s);
const api=window.launcher;
const schema=await (await fetch('./settings.json')).json();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state, page='home',tab='video',draft={},dirty=false,modalDirty=false,save=null,saveList=[],edits={},assets=[],carParts=[],filter='',toastTimer;
async function request(name,...args){const response=await api[name](...args);if(!response.ok)throw Error(response.error);return response.value;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function error(e){const dialog=$('#dialog');if(dialog.open&&dialog.querySelector('form')){let alert=dialog.querySelector('[data-form-error]');if(!alert){alert=document.createElement('p');alert.dataset.formError='';alert.className='banner error';alert.setAttribute('role','alert');alert.tabIndex=-1;dialog.querySelector('form').prepend(alert);}alert.textContent=e.message||String(e);alert.focus();return;}$('#dialog').innerHTML=`<h2>Could not complete the operation</h2><p>${esc(e.message||e)}</p><footer><button data-action="close">Close</button></footer>`;if(!$('#dialog').open)$('#dialog').showModal();}
function title(kicker,heading,description,action=''){return `<div class="row between wrap"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(heading)}</h1><p class="muted">${esc(description)}</p></div>${action}</div>`;}
function source(){return `<div class="hero">${title('Game source',state.ready?'Your copy of Rage Racer':'Start with your copy of the game',state.ready?'Game content follows the loaded disc version.':'Select a legally obtained disc image. The launcher prepares the asset library automatically.')}<div class="card">${state.disc?`<h2>${esc(state.disc.region)}</h2><p class="path">${esc(state.disc.path)}</p><div class="detail">Car names and prologue: <b>${state.disc.region==='NTSC-J'?'Japanese release':'International release'}</b></div>`:'<h2>CUE, CHD or Track 01 BIN</h2><p class="muted">Settings, saves and mod tools become available once the game data is ready.</p>'}<button class="primary" data-action="choose-game" ${state.busy||state.running||!state.toolsReady?'disabled':''}>${state.disc?'Change disc image':'Choose disc image'}</button></div>${!state.toolsReady?'<div class="banner error">This installation is missing its native game tools. Install a complete launcher build.</div>':''}${state.disc&&!state.ready?'<div class="banner warn">The selected image or prepared data is no longer available. Select the image again.</div>':''}</div>`;}
function home(){const active=state.mods.filter(m=>m.enabled);return title('Your game','Rage Racer',`${state.disc.region} · My setup`,`<button class="primary" data-action="play" ${state.running||state.busy||state.conflicts.length?'disabled':''}>${state.running?'Game running':'▷ Play'}</button>`)+`<div class="launch-summary row between"><span><span class="status-dot">●</span> Game data ready · Modern renderer</span><div class="row"><button data-action="logs">View logs</button><button data-page="source">Game source</button></div></div>${state.conflicts.length?'<div class="banner warn">Active mods conflict. Open My mods and choose which overrides to use.</div>':''}<div class="dashboard"><section class="card"><div class="eyebrow">Game saves</div><h2>Continue your progress</h2><p class="muted">Browse local saves or open a memory card.</p><button data-page="saves">Open save editor</button></section><section class="card"><div class="eyebrow">Active mods</div><div class="metric">${active.length||'No'} mods</div><p class="muted">${esc(active.map(m=>m.name).join(', ')||'Original game assets')}</p><button data-page="mods">Manage mods</button></section><section class="card"><div class="eyebrow">Display</div><div class="metric">${esc(state.settings['video.aspect'])} / ${esc(state.settings['video.internal_scale'])}×</div><p class="muted">${esc(state.settings['video.fps'])} · ${esc(state.settings['video.post'])}</p><button data-page="settings">Adjust settings</button></section></div>`;}
function setting(f){const id='setting-'+f.key,value=draft[f.key];let control='';if(f.type==='bool')control=`<input id="${id}" data-setting="${f.key}" type="checkbox" ${value?'checked':''}>`;else if(f.type==='select')control=`<select id="${id}" data-setting="${f.key}">${f.options.map(([v,n])=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(n)}</option>`).join('')}</select>`;else if(f.type==='key')control=`<button id="${id}" type="button" data-bind="${f.key}" aria-label="Bind ${esc(f.label)}">${esc(value)}</button>`;else control=`<input id="${id}" data-setting="${f.key}" type="${f.type==='number'?'number':'text'}" value="${esc(value)}" ${f.type==='number'?`min="${f.min}" max="${f.max}" step="any"`:'maxlength="40"'} required>`;return `<div class="setting"><div><label for="${id}">${esc(f.label)}</label><p>${esc(f.help)}</p></div>${control}</div>`;}
function bindingNotes(){
 const groups=new Map();for(const f of schema.filter(f=>f.type==='key')){const value=String(draft[f.key]||'').toLowerCase();if(!value)continue;if(!groups.has(value))groups.set(value,[]);groups.get(value).push(f);}
 const shared=[...groups.values()].filter(fields=>fields.length>1);
 return shared.length?`<div class="banner warn" data-binding-notes><strong>Shared keys</strong><p>Each key below activates all of its assigned buttons.</p>${shared.map(fields=>`<p><b>${esc(draft[fields[0].key])}</b>: ${fields.map(f=>esc(f.label)).join(', ')}</p>`).join('')}</div>`:'';
}
function settings(){const tabs={video:'Display',hud:'HUD and camera',input:'Controls',advanced:'Advanced'};return title('Configuration','Game settings','Changes apply the next time you launch the game.')+`<nav class="tabs">${Object.entries(tabs).map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav><form id="settings-form"><div class="settings-layout"><section class="card"><h2>${tabs[tab]}</h2>${tab==='input'?bindingNotes():''}${schema.filter(f=>f.group===tab).map(setting).join('')}<div class="sticky-actions"><span id="dirty" class="muted">${dirty?'Unsaved changes':'Saved'}</span><div class="row"><button type="button" data-action="defaults">Restore defaults</button><button class="primary" type="submit" ${state.running?'disabled title="Close the game before saving settings"':''}>Save settings</button></div></div></section><section class="card side-info"><h2>About these settings</h2><p class="muted">Your settings are stored in your user profile. The original game image stays unchanged.</p><div class="detail"><strong>Disc version</strong><p>${esc(state.disc.region)}. Car names and prologue are selected automatically.</p></div><p class="muted">The modern renderer generates its native assets automatically as they are needed.</p></section></div></form>`;}
function saves(){if(!save)return title('Progress','Save editor','Edit a copy while preserving the original.', '<button class="primary" data-action="open-save">Open save or card</button>')+`<section class="card save-list"><h2>Your local saves</h2>${saveList.length?saveList.map(s=>`<button data-save="${esc(s.id)}"><strong>${esc(s.team||'Unnamed team')}</strong><br><small>${s.money.toLocaleString('en-US')} credits</small></button>`).join(''):'<p class="muted">No local saves found. Open an existing save or memory card to begin.</p>'}</section>`;
 if(save.card)return title('Memory card',save.name,'Choose the Rage Racer save to edit.')+`<section class="card save-list">${save.entries.map(e=>`<button data-card="${e.index}">${esc(e.team)} <small>${esc(e.name)}</small></button>`).join('')||'<p>No Rage Racer saves on this card.</p>'}</section>`;
 return title('Save editor',save.name,'Changes are written to a separate copy.', '<button data-action="other-save">Choose another save</button>')+`${!save.checksumsValid?'<div class="banner warn">The original has checksum errors. Saving a copy will recalculate them.</div>':''}<form id="save-form"><section class="card"><button type="button" data-action="edit-logo">Edit team logo</button> <label for="team">Team name</label><input id="team" data-team maxlength="7" value="${esc(edits.team??save.team)}"><div class="toolbar"><input id="field-search" type="search" placeholder="Filter by car name, credits, lap, driver…" aria-label="Filter save fields" value="${esc(filter)}"></div><div class="save-fields">${save.fields.map(field).join('')}</div><div class="sticky-actions"><span id="dirty" class="muted">${dirty?'Unsaved changes':'Original preserved'}</span><button type="submit" class="primary" ${state.running?'disabled':''}>Save a copy</button></div></section></form>`;
}
// Menu swatches from g_PaintColorTable in src/port/host_state_menu.c.
const paintColors=["#989878","#002040","#a08010","#909090","#985020","#303840","#107028","#803020","#405080","#882020","#243058","#a03838","#181818","#884878","#283020","#988848","#608090","#586848"];
function field(f){const value=edits[f.key]??f.value;const cars=save.carNames?.[state.disc.region==='NTSC-J'?'japanese':'international']||[];const labels={padMappingIndex:'Controller / Button preset',negconMappingIndex:'neGcon / Button preset',negconSteerNeutral:'neGcon / Steering centre',negconSteerPlay:'neGcon / Steering dead zone',negconNeutralI:'neGcon / I button neutral',negconNeutralII:'neGcon / II button neutral',negconNeutralL:'neGcon / L button neutral',negconMaxTwist:'neGcon / Maximum twist',bgmSelection:'Audio / Music selection',bgmVolume:'Audio / Music volume',sfxVolume:'Audio / Sound effects volume',monoOutput:'Audio / Output',extraGrandPrixUnlocked:'Progress / Extra Grand Prix'};const label=labels[f.key]||f.key.replace(/Car (\d{2})/g,(_,index)=>cars[Number(index)]||'Car '+index);const name=esc(label);const key=esc(f.key);const numeric=Number(value);let control;const choice=f.key==='monoOutput'?['Stereo','Mono']:f.key==='extraGrandPrixUnlocked'?['Locked','Unlocked']:f.key.endsWith(' / Transmission')?['Automatic','Manual']:f.key.endsWith(' / Owned')?['Not owned','Owned']:f.key.endsWith(' / Car')?cars:null;
 if(/ \/ Paint [12]$/.test(f.key))control=`<fieldset class="paint-palette"><legend>${name}</legend>${numeric<0||numeric>=paintColors.length?`<small>Unknown color (${esc(value)}) — preserved until changed</small>`:''}<div>${paintColors.map((color,i)=>`<label title="Color ${i}"><input type="radio" name="paint-${key}" data-field="${key}" value="${i}" aria-label="${name}: color ${i}" ${numeric===i?'checked':''}><span style="background:${color}">${i}</span></label>`).join('')}</div></fieldset>`;
 else if(f.text)control=`<input aria-label="${name}" data-field="${key}" type="text" maxlength="${f.maxLength}" value="${esc(value)}">`;
 else if(choice?.length)control=`<select aria-label="${name}" data-field="${key}">${(!Number.isInteger(numeric)||numeric<0||numeric>=choice.length)?`<option value="${esc(value)}" selected>Unknown value (${esc(value)}) — preserved</option>`:''}${choice.map((label,i)=>`<option value="${i}" ${numeric===i?'selected':''}>${esc(label)}</option>`).join('')}</select>`;
 else
 if(f.time&&numeric>=0)control=`<div class="time-segments"><input aria-label="${name}: minutes" data-time="${key}" data-part="m" type="number" min="0" max="35791" value="${Math.floor(numeric/60000)}" required><span>:</span><input aria-label="${name}: seconds" data-time="${key}" data-part="s" type="number" min="0" max="59" value="${Math.floor(numeric/1000)%60}" required><span>.</span><input aria-label="${name}: milliseconds" data-time="${key}" data-part="ms" type="number" min="0" max="999" value="${numeric%1000}" required></div>`;
 else control=`<input aria-label="${name}" data-field="${key}" type="number" min="${f.min}" max="${f.max}" step="1" value="${esc(value)}" required>`;
 return `<div class="save-field" data-search="${esc((label+' '+f.key).toLowerCase())}" ${filter&&!(label+' '+f.key).toLowerCase().includes(filter.toLowerCase())?'hidden':''}><div>${name}${f.time?'<small> · min : sec . ms</small>':''}${f.time&&numeric<0?'<small> · special stored value</small>':''}</div>${control}</div>`;
}
function modCarPreviews(mod){return Object.keys(mod.manifest.meshes||{}).flatMap(key=>{
 const match=/^car\.(player|rival)\.(\d+)\.part\.(\d+)$/.exec(key);if(!match)return [];
 const rival=match[1]==='rival',part=Number(match[3]);if(rival?part%5!==0:part!==0)return [];
 return [`<button data-whole-car="${match[2]}" data-whole-body="${part}" data-whole-rival="${rival}" data-whole-mod="${esc(mod.id)}">Preview car · ${match[2]}${rival?' / '+part:''}</button>`];
}).join('');}
const openModModels=new Set();
function modModels(mod){
 const keys=Object.keys(mod.manifest.meshes||{});if(!keys.length)return '';
 const groups=new Map();
 for(const key of keys){const match=/^car\.(player|rival)\.(\d+)\.part\.(\d+)$/.exec(key);const group=match?match[1]+' · Bank '+match[2]:'Other models';if(!groups.has(group))groups.set(group,[]);groups.get(group).push(key);}
 return `<details class="mod-models" data-mod-models="${esc(mod.id)}" ${openModModels.has(mod.id)?'open':''}><summary>Models · ${keys.length} replaced parts</summary><div class="mod-model-list">${[...groups].map(([name,parts])=>`<section><h4>${esc(name)}</h4><div class="row wrap">${modCarPreviews({...mod,manifest:{meshes:Object.fromEntries(parts.map(key=>[key,true]))}})}</div><div class="row wrap">${parts.sort((a,b)=>Number(a.split('.').at(-1))-Number(b.split('.').at(-1))).map(key=>`<button data-preview-car="${esc(key)}" data-preview-mod="${esc(mod.id)}">Preview part ${esc(key.split('.').at(-1))}</button>`).join('')}</div></section>`).join('')}</div></details>`;
}
document.addEventListener('toggle',e=>{const id=e.target.dataset?.modModels;if(id&&e.target.isConnected){if(e.target.open)openModModels.add(id);else openModModels.delete(id);}},true);
function mods(){const duplicates=duplicatePackageIds(state.mods);return title('Library','My mods','Import a folder containing raw overrides, textures or a mod.toml manifest.','<button class="primary" data-action="import-mod">Import mod folder</button>')+`${state.overlaps?.length?`<section class="card" style="margin-bottom:20px"><h2>Override priorities</h2><p class="muted">Choose a provider for each overlap. Other changes from both mods stay enabled.</p>${state.overlaps.map(c=>`<div class="setting"><label for="priority-${esc(c.key)}">${esc(c.key)}<p>${c.winner?'Priority saved':'Choose a provider before playing'}</p></label><select id="priority-${esc(c.key)}" data-conflict="${esc(c.key)}" ${state.running?'disabled':''}><option value="" ${!c.winner?'selected':''} disabled>Choose provider…</option>${c.candidates.map(m=>`<option value="${esc(m.id)}" ${c.winner===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></div>`).join('')}</section>`:''}<section class="card">${state.mods.map(m=>`<div class="mod"><input type="checkbox" data-mod="${esc(m.id)}" aria-label="Enable ${esc(m.name)}" ${m.enabled?'checked':''} ${state.running?'disabled':''}><div class="thumb">◇</div><div class="mod-details"><h3>${esc(m.name)}</h3>${m.requires?.length?`<p class="muted">Requires: ${m.requires.map(d=>esc(requirementLabel(d))+' · '+esc(requirementNote(requirementStatus(m,d,state.mods)))).join(", ")}</p>`:""}${duplicates.has(packageIdOf(m))?`<p class="muted">Duplicate package ID ${esc(packageIdOf(m))}: another installed mod uses it, so only one copy can be enabled at a time.</p>`:""}<small>${m.files.length} files · ${esc(m.region)}${m.version?` · Version ${esc(m.version)}`:""}${m.author?` · By ${esc(m.author)}`:""}</small>${m.description?`<details class="mod-description-details"><summary>Description</summary><p class="mod-description">${esc(m.description)}</p></details>`:""}</div><div class="row wrap">${modCarBanks(m).size?`<button data-appearance-mod="${esc(m.id)}">Preview appearance</button>`:''}<button data-mod-details="${esc(m.id)}">Details</button><button data-material-mod="${esc(m.id)}">Materials</button><button data-export-mod="${esc(m.id)}">Export</button><button data-remove-mod="${esc(m.id)}">Remove</button></div>${modModels(m)}</div>`).join('')||'<div class="empty"><h2>No mods installed</h2><p class="muted">Import a mod folder to inspect and enable its changes.</p></div>'}</section>`;}
let carSection='player',selectedCar='',rivalClass=1,rivalCourse=0;
function cars(){
 const bodies=carParts.filter(c=>c.rival?c.part%5===0:c.part===0).filter(c=>c.rival===(carSection==='rival')&&(!c.rival||c.bank===88+(rivalClass-1)*8+rivalCourse*2)).sort((a,b)=>a.bank-b.bank||a.part-b.part);
 const car=bodies.find(c=>c.key===selectedCar)||bodies[0];
 if(!car)return title('Workshop','Car models','No cars found.');
 selectedCar=car.key;
 const slot=(car.bank-10)/2,course=['Grand Valley','Over Pass','Lakeside Gate','Extreme Oval'][((car.bank-88)/2)%4],raceClass=Math.floor((car.bank-88)/8)+1;
 const parts=carParts.filter(c=>c.bank===car.bank&&c.rival===car.rival&&(!car.rival||c.part>=car.part&&c.part<car.part+5));
 return title('Workshop','Car models','Choose a slot, then work on the complete car.')+
 '<div class="row car-sections" role="group" aria-label="Car category">'+['player','rival'].map(k=>'<button data-car-section="'+k+'" aria-pressed="'+(carSection===k)+'" class="'+(carSection===k?'primary':'')+'">'+(k==='player'?'Player slots · 0–31':'Rival cars')+'</button>').join('')+'</div>'+
 (carSection==='rival'?'<div class="row car-sections"><label>Race class <select data-rival-filter="class">'+Array.from({length:6},(_,i)=>'<option value="'+(i+1)+'" '+(rivalClass===i+1?'selected':'')+'>Class '+(i+1)+'</option>').join('')+'</select></label><label>Course <select data-rival-filter="course">'+['Grand Valley','Over Pass','Lakeside Gate','Extreme Oval'].map((n,i)=>'<option value="'+i+'" '+(rivalCourse===i?'selected':'')+'>'+n+'</option>').join('')+'</select></label></div>':'')+
 '<div class="car-workshop"><nav class="card car-slots" aria-label="Car slots">'+bodies.map(c=>'<button data-select-car="'+c.key+'" aria-current="'+(c.key===car.key)+'"><strong>'+(!c.rival?'Slot '+String((c.bank-10)/2).padStart(2,'0'): 'Model '+(c.part/5))+'</strong><span>'+esc(c.name)+'</span></button>').join('')+'</nav><section class="card car-project"><small>'+(!car.rival?'PLAYER SLOT '+String(slot).padStart(2,'0'):'RIVAL · CLASS '+raceClass+' · '+course)+'</small><h2>'+esc(car.name)+'</h2><p class="muted">Body, front wheels, rear wheels and their textures form one car set.</p><div class="row wrap"><button class="primary" data-whole-car="'+car.bank+'" data-whole-body="'+car.part+'" data-whole-rival="'+car.rival+'">Preview car</button><button data-export-set="'+car.key+'">Export car set</button><button data-import-set="'+car.key+'">Import car set</button></div><div class="car-components">'+['Body + textures','Front wheels + textures','Rear wheels + textures'].map(t=>'<div><strong>'+t+'</strong><p class="muted">From your game image</p></div>').join('')+'</div>'+carInstalledChanges(car)+(!car.rival?'<h3>Driving & transmission</h3><p class="muted">Engine limits, MT-only availability and automatic shift points.</p><button data-car-spec="'+car.bank+'">Edit car parameters</button>':'')+'<details class="car-advanced"><summary>Advanced · individual parts</summary><p class="muted">Use these actions to replace a single mesh. Texture changes belong in the car set.</p>'+parts.map(c=>'<div class="setting"><span>'+esc(c.name)+' · Part '+c.part+'</span><div class="row wrap"><button data-preview-car="'+c.key+'">Preview</button><button data-export-car="'+c.key+'">Export mesh</button><button data-import-car="'+c.key+'">Replace mesh</button></div></div>').join('')+'</details></section></div>';
}

function carInstalledChanges(car){
 const related=state.mods.map(mod=>({mod,...carModChanges(mod,car)})).filter(m=>m.affected);
 return '<section class="car-installed"><h3>Installed changes</h3>'+(!related.length?'<p class="muted">No installed mods target this car yet.</p>':'<p class="muted">Previews show one mod at a time. Resolve overlapping changes in My mods.</p>'+related.map(({mod,preview,raw})=>`<div class="setting"><label><input type="checkbox" data-mod="${esc(mod.id)}" ${mod.enabled?'checked':''} ${state.running||mod.region!==state.disc.region?'disabled':''}> ${esc(mod.name)}<p>${mod.enabled?'Enabled':'Disabled'}${mod.region!==state.disc.region?' · Different game version':''}${raw?' · Raw model or driving-data changes':''}</p></label><div>${preview&&mod.region===state.disc.region?`<button data-whole-car="${car.bank}" data-whole-body="${car.part}" data-whole-rival="${car.rival}" data-whole-mod="${esc(mod.id)}">Preview mod</button>`:''}${raw?'<small>Raw changes are not shown in the 3D preview.</small>':''}</div></div>`).join(''))+'</section>';
}

function library(){return title('Workshop','Asset library','Raw entries extracted from your disc. Export an entry for external editing.')+`<section class="card"><p class="muted">These are archive entries, not necessarily individual models. Keep replacements in a mod folder under raw/ using the same file name.</p><div class="table-scroll"><table class="asset-table"><thead><tr><th>Entry</th><th>Size</th><th></th></tr></thead><tbody>${assets.filter(a=>a.present!==false).map(a=>`<tr><td>asset_${String(a.index).padStart(3,'0')}.bin</td><td>${a.size.toLocaleString('en-US')} bytes</td><td><button data-export-asset="${a.index}">Export</button> <button data-replace-asset="${a.index}">Import replacement</button></td></tr>`).join('')}</tbody></table></div></section>`;}
function render(){
 if(!state)return;const unlocked=state.ready&&!state.busy;
 $('#status').textContent=state.running?'Game running':state.busy||(!state.ready?'No game loaded':state.disc.region);
 $('#nav').querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.disabled=(!unlocked&&!['home','source'].includes(b.dataset.page));});
 $('#main').innerHTML=(state.busy?`<div class="busy"><span><i class="spinner"></i>${esc(state.busy)}</span><button data-action="cancel" ${state.canCancel?'':'disabled'}>Cancel</button></div>`:'')+(state.error?`<div class="banner error">${esc(state.error)} <button data-action="logs">View logs</button></div>`:'')+(!state.ready||page==='source'?source():({home,settings,saves,mods,assets:library,cars}[page])());
}
document.addEventListener('change',e=>{if(e.target.dataset.rivalFilter){if(e.target.dataset.rivalFilter==='class')rivalClass=Number(e.target.value);else rivalCourse=Number(e.target.value);selectedCar='';render();}});
async function navigate(next){if(next===page)return;if(dirty){$('#dialog').innerHTML=`<h2>Discard unsaved changes?</h2><p>Your edits have not been saved.</p><footer><button data-action="close">Keep editing</button><button data-discard="${next}">Discard and continue</button></footer>`;$('#dialog').showModal();return;}await enter(next);}
async function enter(next){if(!state.ready&&!['home','source'].includes(next))return;page=next;if(page==='settings')draft={...state.settings};if(page==='saves'&&!save)saveList=await request('saves');if(page==='cars')carParts=(await request('cars')).parts;if(page==='assets')assets=(await request('assets')).entries;render();}
async function perform(task){try{await task();}catch(e){if(e.message==='Operation canceled')toast('Operation canceled. Your previous game data is unchanged.');else error(e);}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(!b.type||b.type==='submit'){if(b.closest('form')&&!b.dataset.action&&!b.dataset.tab)return;}e.preventDefault();perform(async()=>{
 if(b.dataset.action==='logs'){const logs=await request('logs');$('#dialog').innerHTML='<h2>Game logs</h2><p class="muted">Recent output from the last game sessions. Logs can contain local file paths.</p>'+logs.map(log=>`<h3>${esc(log.name)}</h3>${log.truncated?'<p class="muted">Showing the last 64 KiB.</p>':''}<pre class="log-output" tabindex="0">${esc(log.missing?'No log yet. Launch the game to create it.':log.text||'The log is empty.')}</pre>`).join('')+'<footer><button data-action="close">Close</button></footer>';$('#dialog').showModal();return;}
 if(b.dataset.bind){const key=b.dataset.bind;$('#dialog').innerHTML='<h2>Choose a key</h2><p>Press a keyboard key. Bindings use physical key positions.</p><p class="muted" data-key-hint>Press Escape to cancel.</p><footer><button data-action="close">Cancel</button></footer>';const dialog=$('#dialog');const capture=e=>{if(e.key==='Escape')return;e.preventDefault();e.stopPropagation();const name=bindingName(e.code);if(!name){dialog.querySelector('[data-key-hint]').textContent='This key is not supported. Choose another key.';return;}draft[key]=name;dirty=true;dialog.close();render();};dialog.addEventListener('keydown',capture);dialog.addEventListener('close',()=>dialog.removeEventListener('keydown',capture),{once:true});dialog.showModal();return;}
 if(b.dataset.carSection){carSection=b.dataset.carSection;selectedCar='';render();return;}
 if(b.dataset.selectCar){selectedCar=b.dataset.selectCar;render();return;}
 if(b.dataset.exportSet){if(await request('exportCarSet',b.dataset.exportSet))toast('Complete car set exported');return;}
 if(b.dataset.importSet){if(await request('importCarSet',b.dataset.importSet))toast('Car set imported as one mod. Enable it in My mods.');return;}
 if(b.dataset.page)return navigate(b.dataset.page);
 if(b.dataset.discard){dirty=false;edits={};draft={...state.settings};$('#dialog').close();return enter(b.dataset.discard);}
 if(b.dataset.tab){if(!$('#settings-form').reportValidity())return;tab=b.dataset.tab;render();return;}
 if(b.dataset.save!==undefined){save=await request('openSave',b.dataset.save);edits={};render();return;}
 if(b.dataset.card!==undefined){save=await request('cardEntry',Number(b.dataset.card));edits={};render();return;}
 if(b.dataset.carSpec!==undefined){const bank=Number(b.dataset.carSpec);carSpecDialog(bank,await request('carSpec',bank));return;}
 if(b.dataset.modDetails){const mod=state.mods.find(m=>m.id===b.dataset.modDetails);$('#dialog').innerHTML='<h2>Mod details</h2><p class="muted">Package ID: '+esc(mod.packageId||mod.id)+'</p><form id="mod-details-form" data-mod="'+esc(mod.id)+'">'+[['name','Name',200],['author','Author',120],['version','Version',80],['description','Description',1200]].map(([key,label,max])=>'<div class="setting"><label for="mod-detail-'+key+'">'+label+'</label>'+(key==='description'?'<textarea id="mod-detail-'+key+'" data-detail="'+key+'" maxlength="'+max+'" rows="5">'+esc(mod[key]||'')+'</textarea>':'<input id="mod-detail-'+key+'" data-detail="'+key+'" maxlength="'+max+'" '+(key==='name'?'required':'')+' value="'+esc(mod[key]||'')+'">')+'</div>').join('')+'<footer><button type="button" data-action="close">Cancel</button><button class="primary" type="submit">Save details</button></footer></form>';$('#dialog').showModal();return;}
 if(b.dataset.appearanceMod){const mod=state.mods.find(m=>m.id===b.dataset.appearanceMod);const catalog=await request('cars');const targets=modCarTargets(mod,catalog.parts);$('#dialog').innerHTML=`<h2>Preview appearance</h2><p class="muted">Choose a car from the model banks this mod changes. Some materials may only be used by certain parts.</p><div class="save-list mod-model-list">${targets.map(c=>`<button data-whole-car="${c.bank}" data-whole-body="${c.part}" data-whole-rival="${c.rival}" data-whole-mod="${esc(mod.id)}">${esc(c.name)} <small>· ${c.rival?'Rival':'Player'} · Bank ${c.bank}</small></button>`).join('')||'<p>No supported car models found for these materials.</p>'}</div><footer><button data-action="close">Close</button></footer>`;$('#dialog').showModal();return;}
 if(b.dataset.wholeCar!==undefined){const args=[Number(b.dataset.wholeCar),Number(b.dataset.wholeBody||0),b.dataset.wholeRival==='true'];const modified=await request('previewWholeCar',...args,b.dataset.wholeMod);const options=b.dataset.wholeMod?{comparison:{modified,original:await request('previewWholeCar',...args)},mode:'modified'}:{};await mountModelPreview($('#dialog'),modified,options);return;}
 if(b.dataset.previewCar){await mountModelPreview($('#dialog'),await request('previewCar',b.dataset.previewCar,b.dataset.previewMod));return;}
 if(b.dataset.importCar){if(await request('importCar',b.dataset.importCar))toast('Car replacement imported. Enable it in My mods.');return;}
 if(b.dataset.exportCar){if(await request('exportCar',b.dataset.exportCar))toast('Model folder exported');return;}
 if(b.dataset.exportAsset!==undefined){if(await request('exportAsset',Number(b.dataset.exportAsset)))toast('Asset exported');return;}
 if(b.dataset.replaceAsset!==undefined){if(await request('replaceAsset',Number(b.dataset.replaceAsset)))toast('Replacement imported as a disabled mod. Enable it in My mods.');return;}
 if(b.dataset.editMaterial!==undefined){materialDialog(b.dataset.modId,b.dataset.editMaterial||null);return;}
 if(b.dataset.materialMod){materialDialog(b.dataset.materialMod);return;}
 if(b.dataset.removeMod)return request('removeMod',b.dataset.removeMod);
 if(b.dataset.exportMod){if(await request('exportMod',b.dataset.exportMod))toast('Mod folder exported');return;}
 const a=b.dataset.action;
 if(a==='close')$('#dialog').close();
 if(a==='edit-logo'){
  const logo={pixels:edits['logo.pixels']??save.logo.pixels,colors:save.logo.colors.map((c,i)=>{const v=edits['logo.color.'+i];return v?{rgb:'#'+v.slice(0,6),transparent:v[6]==='1'}:{...c};})};
  mountLogo($('#dialog'),logo,result=>{if(result.pixels!==logo.pixels)edits['logo.pixels']=result.pixels;result.colors.forEach((c,i)=>{if(c.rgb!==logo.colors[i].rgb||c.transparent!==logo.colors[i].transparent)edits['logo.color.'+i]=c.rgb.slice(1)+(c.transparent?'1':'0');});dirty=Object.keys(edits).length>0;$('#dialog').close();render();},()=>$('#dialog').close(),changed=>{modalDirty=changed;});$('#dialog').showModal();
 }

 if(a==='choose-game')await request('chooseGame');
 if(a==='cancel')await request('cancel');
 if(a==='play')await request('play');
 if(a==='defaults'){draft=Object.fromEntries(schema.map(f=>[f.key,f.default]));dirty=true;render();}
 if(a==='open-save'){const data=await request('openSave');if(data){save=data;edits={};dirty=false;render();}}
 if(a==='other-save'){if(dirty){toast('Save your copy or leave this page to discard edits first.');return;}save=null;saveList=await request('saves');render();}
 if(a==='import-mod')await request('importMod');
 });});
$('#dialog').addEventListener('close',()=>{modalDirty=false;});
document.addEventListener('paste',e=>{
 if(!e.target.dataset.time)return;
 const text=e.clipboardData?.getData('text/plain')??'';
 // Leave a plain numeric paste to the focused segment's native input behavior.
 if(!text.includes(':'))return;
 e.preventDefault();
 const time=parseTimeClipboard(text);
 if(!time){toast('Use minutes:seconds.milliseconds, for example 01:40.765, within the save format limit.');return;}
 const row=e.target.closest('.time-segments');
 for(const input of row.querySelectorAll('input'))input.value=String(time[input.dataset.part]);
 e.target.dispatchEvent(new Event('input',{bubbles:true}));
});
document.addEventListener('input',e=>{
 if(e.target.closest('#material-form, #car-spec-form, #mod-details-form'))modalDirty=true;
 if(e.target.dataset.setting){draft[e.target.dataset.setting]=e.target.type==='checkbox'?e.target.checked:e.target.value;dirty=true;}
 if(e.target.hasAttribute('data-team')){edits.team=e.target.value;dirty=true;}
 if(e.target.dataset.field){edits[e.target.dataset.field]=e.target.value;dirty=true;}
 if(e.target.dataset.time){const row=e.target.closest('.time-segments');const parts=[...row.querySelectorAll('input')];const value=Number(parts[0].value)*60000+Number(parts[1].value)*1000+Number(parts[2].value);parts[0].setCustomValidity(value>2147483647?'Time exceeds the save format limit':'');if(parts.every(p=>p.validity.valid&&p.value!==''))edits[e.target.dataset.time]=value;dirty=true;}
 if(e.target.id==='field-search'){filter=e.target.value;document.querySelectorAll('.save-field').forEach(f=>f.hidden=!f.dataset.search.includes(filter.toLowerCase()));}
 if(dirty&&$('#dirty'))$('#dirty').textContent='Unsaved changes';
});
document.addEventListener('change',e=>{if(e.target.dataset.conflict)perform(async()=>{await request('resolveConflict',e.target.dataset.conflict,e.target.value);});if(e.target.dataset.mod)perform(async()=>{await request('toggleMod',e.target.dataset.mod,e.target.checked);});});
document.addEventListener('submit',e=>{e.preventDefault();e.target.querySelector('[data-form-error]')?.remove();perform(async()=>{
 if(e.target.id==='mod-details-form'){const values=Object.fromEntries([...e.target.querySelectorAll('[data-detail]')].map(i=>[i.dataset.detail,i.value]));await request('saveModDetails',e.target.dataset.mod,values);$('#dialog').close();toast('Mod details saved');return;}
 if(e.target.id==='car-spec-form'){const edits=Object.fromEntries([...e.target.querySelectorAll('[data-spec]')].filter(i=>i.value!==(i.dataset.original??i.defaultValue)).map(i=>[i.dataset.spec,i.dataset.speed?storedShiftSpeed(Number(i.value)):Number(i.value)]));if(!Object.keys(edits).length){toast('Change a parameter before saving');return;}await request('saveCarSpec',Number(e.target.dataset.bank),edits);$('#dialog').close();toast('Parameters saved as a disabled mod. Enable it in My mods.');return;}
 if(e.target.id==='material-form'){const target=$('#material-key');if(!target.readOnly&&Object.hasOwn(state.mods.find(m=>m.id===e.target.dataset.mod).manifest.materials,target.value))throw Error('This material already exists. Close this form and choose it from the material list.');const values=[...e.target.querySelectorAll('[data-property]')].map(i=>i.value);await request('saveMaterial',e.target.dataset.mod,$('#material-key').value,values.join(' '));$('#dialog').close();toast('Material saved to the mod');return;}
 if(e.target.id==='settings-form'){state=await request('settings',draft);dirty=false;render();toast('Settings saved');}
 if(e.target.id==='save-form'){const data=await request('saveCopy',edits);if(data){dirty=false;edits={};save=null;saveList=await request('saves');render();toast('Separate copy saved with updated checksums');}}
 });});
window.addEventListener('beforeunload',e=>{if(dirty||modalDirty){e.preventDefault();e.returnValue='';}});
api.onState(value=>{state=value;if(!dirty)draft={...value.settings};if(!dirty||value.busy)render();});
await perform(async()=>{state=await request('snapshot');draft={...state.settings};render();});

function materialDialog(id,selected){const mod=state.mods.find(m=>m.id===id);const keys=Object.keys(mod.manifest.materials);
 if(selected===undefined&&keys.length){$('#dialog').innerHTML=`<h2>Materials</h2><p class="muted">Choose a material to edit its stored values.</p><div class="material-list">${keys.map(key=>`<button type="button" data-edit-material="${esc(key)}" data-mod-id="${esc(id)}">${esc(key)}</button>`).join('')}</div><footer><button type="button" data-action="close">Close</button><button type="button" data-edit-material="" data-mod-id="${esc(id)}">Add material</button></footer>`;$('#dialog').showModal();return;}
 const key=selected||'car.0.material.0';const values=(mod.manifest.materials[key]||'lit opaque 0.35 0 1 1 1 1 0 0 0').split(/\s+/);const labels=['Shading','Transparency','Roughness','Metallic','Red','Green','Blue','Opacity','Emission red','Emission green','Emission blue'];$('#dialog').innerHTML=`<h2>Edit material</h2><p class="muted">Parameters are validated by the game renderer. Save to the mod, then test it in the game.</p><form id="material-form" data-mod="${esc(id)}"><label for="material-key">Material ID</label><input id="material-key" value="${esc(key)}" pattern="[a-z0-9.-]+" required ${selected?'readonly':''}>${labels.map((label,i)=>`<div class="setting"><label for="property-${i}">${label}</label>${i<2?`<select id="property-${i}" data-property>${(i===0?['inherit','lit','unlit']:['auto','opaque','mask','blend']).map(v=>`<option ${values[i]===v?'selected':''}>${v}</option>`).join('')}</select>`:`<input id="property-${i}" data-property type="number" min="0" max="1" step="any" value="${esc(values[i])}" required>`}</div>`).join('')}<footer><button type="button" data-action="close">Cancel</button><button class="primary" type="submit">Save material</button></footer></form>`;$('#dialog').showModal();}


function carSpecDialog(bank,data){
 const labels={revLimit:['Rev limit','Engine RPM ceiling.'],redline:['Redline','Engine RPM at the redline warning.'],topGear:['Forward gears','Highest gear available to this car.'],automaticAccelerationScale:['Automatic acceleration scale','Per thousand: 1000 = 100%.']};
 const car=carParts.find(p=>p.bank===bank&&!p.rival&&p.part===0);
 const input=f=>{const speed=/^(downshift|upshift)/.test(f.key),value=speed?displayedShiftSpeed(f.value):f.value,min=speed?displayedShiftSpeed(f.min):f.min,max=speed?displayedShiftSpeed(f.max):f.max;return '<input id="spec-'+f.key+'" aria-label="'+f.key+'" data-spec="'+f.key+'" '+(speed?'data-speed="true" ':'')+'type="number" min="'+min+'" max="'+max+'" step="'+(speed?'0.01':'1')+'" value="'+value+'" required>';};
 const manual=data.fields.find(f=>f.key==='manualOnly');
 $('#dialog').innerHTML='<h2>Driving & transmission</h2><p>Slot '+((bank-10)/2)+' · '+esc(car?.name)+'</p><p class="muted">Starting values come from your disc. Save creates one separate mod.</p><form id="car-spec-form" data-bank="'+bank+'"><div class="setting"><label for="spec-manualOnly">Transmission availability<p>MT-only removes the automatic option in the game.</p></label><select id="spec-manualOnly" data-spec="manualOnly" data-original="'+manual.value+'"><option value="0" '+(!manual.value?'selected':'')+'>AT and MT</option><option value="1" '+(manual.value?'selected':'')+'>MT only</option></select></div>'+data.fields.filter(f=>labels[f.key]).map(f=>'<div class="setting"><label for="spec-'+f.key+'">'+labels[f.key][0]+'<p>'+labels[f.key][1]+'</p></label>'+input(f)+'</div>').join('')+'<h3>Automatic shift points</h3><p class="muted">Speeds match the in-game speedometer. These settings are used when AT is available. Values for unused gears are kept.</p><table class="asset-table"><thead><tr><th>Gear</th><th>Shift down below</th><th>Shift up above</th></tr></thead><tbody>'+Array.from({length:6},(_,i)=>'<tr><th>'+(i+1)+'</th><td>'+input(data.fields.find(f=>f.key==='downshift'+(i+1)))+'</td><td>'+input(data.fields.find(f=>f.key==='upshift'+(i+1)))+'</td></tr>').join('')+'</tbody></table><footer><button type="button" data-action="close">Cancel</button><button class="primary" type="submit">Save as mod</button></footer></form>';
 $('#dialog').classList.add('car-parameters-dialog');$('#dialog').addEventListener('close',()=>$('#dialog').classList.remove('car-parameters-dialog'),{once:true});$('#dialog').showModal();
}
