string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT_ROOT}/runtime-config-${id}")
set(assets "${root}/native-assets")
file(MAKE_DIRECTORY "${assets}")
execute_process(COMMAND "${FIXTURE}" "${assets}" RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Cannot generate fixture: ${root}")
endif()
set(scenario "${root}/scenario.ini")
file(WRITE "${scenario}" "[race]\nmode=grand-prix\nseries=extra-gp\nclass=2\ncourse=1\ncar=4\n[video]\nrenderer=classic\ntoggle_renderer_key=F9\n[modern]\nassets=${assets}\n[run]\nframes=2700\n[stop]\nscene=12\ntimer=100\n[hooks]\ntoggle_renderer_frame=230\n")
# Prove the INI path alone, regardless of developer runtime overrides.
execute_process(COMMAND "${CMAKE_COMMAND}" -E environment OUTPUT_VARIABLE environment
    RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Cannot inspect environment")
endif()
string(REGEX MATCHALL "(^|\n)RAGE_PORT_[^=\r\n]+=" variables "${environment}")
set(unset)
foreach(variable IN LISTS variables)
    string(STRIP "${variable}" variable)
    string(REGEX REPLACE "=$" "" variable "${variable}")
    list(APPEND unset "--unset=${variable}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${unset} SDL_AUDIODRIVER=dummy
    "${GAME}" --scenario "${scenario}" WORKING_DIRECTORY "${SOURCE}"
    TIMEOUT 150 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(log "${output}${error}")
file(WRITE "${root}/game.log" "${log}")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Runtime config failed (${result}): ${root}")
endif()
foreach(required "renderer toggle=F9; active=classic" "renderer switched to modern"
    "scenario mode=grand-prix series=extra-gp class=2 course=1 car=4" "scene 12")
    string(FIND "${log}" "${required}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Missing ${required}: ${root}")
    endif()
endforeach()
if(NOT log MATCHES "capture_faces=([0-9]+)" OR CMAKE_MATCH_1 EQUAL 0)
    message(FATAL_ERROR "Toggle did not activate semantic capture: ${root}")
endif()
message(STATUS "Compiled runtime config passed: ${root}")
