const {contextBridge,ipcRenderer}=require('electron');
// Deliberately expose one bounded operation per message, never arbitrary IPC.
contextBridge.exposeInMainWorld('launcher',Object.freeze({
  snapshot:()=>ipcRenderer.invoke('launcher:snapshot'),
  logs:()=>ipcRenderer.invoke('launcher:logs'),
  chooseGame:()=>ipcRenderer.invoke('launcher:choose-game'),
  cancel:()=>ipcRenderer.invoke('launcher:cancel'),
  settings:values=>ipcRenderer.invoke('launcher:settings',values),
  play:()=>ipcRenderer.invoke('launcher:play'),
  saves:()=>ipcRenderer.invoke('launcher:saves'),
  openSave:id=>ipcRenderer.invoke('launcher:open-save',id),
  cardEntry:index=>ipcRenderer.invoke('launcher:card-entry',index),
  saveCopy:edits=>ipcRenderer.invoke('launcher:save-copy',edits),
  assets:()=>ipcRenderer.invoke('launcher:assets'),
  cars:()=>ipcRenderer.invoke('launcher:cars'),
  exportCarSet:key=>ipcRenderer.invoke('launcher:export-car-set',key),
  importCarSet:key=>ipcRenderer.invoke('launcher:import-car-set',key),
  previewWholeCar:(bank,body,rival,modId)=>ipcRenderer.invoke('launcher:preview-whole-car',bank,body,rival,modId),
  carSpec:bank=>ipcRenderer.invoke('launcher:car-spec',bank),
  saveCarSpec:(bank,edits)=>ipcRenderer.invoke('launcher:save-car-spec',bank,edits),
  previewCar:(key,modId)=>ipcRenderer.invoke('launcher:preview-car',key,modId),
  exportCar:key=>ipcRenderer.invoke('launcher:export-car',key),
  importCar:key=>ipcRenderer.invoke('launcher:import-car',key),
  exportAsset:index=>ipcRenderer.invoke('launcher:export-asset',index),
  replaceAsset:index=>ipcRenderer.invoke('launcher:replace-asset',index),
  saveMaterial:(id,key,properties)=>ipcRenderer.invoke('launcher:save-material',id,key,properties),
  importMod:()=>ipcRenderer.invoke('launcher:import-mod'),
  saveModDetails:(id,details)=>ipcRenderer.invoke('launcher:save-mod-details',id,details),
  toggleMod:(id,enabled)=>ipcRenderer.invoke('launcher:toggle-mod',id,enabled),
  resolveConflict:(key,winner)=>ipcRenderer.invoke('launcher:resolve-conflict',key,winner),
  removeMod:id=>ipcRenderer.invoke('launcher:remove-mod',id),
  exportMod:id=>ipcRenderer.invoke('launcher:export-mod',id),
  onState:listener=>{const fn=(_event,state)=>listener(state);ipcRenderer.on('launcher:state',fn);return()=>ipcRenderer.removeListener('launcher:state',fn);}
}));
