file(MAKE_DIRECTORY "${EVIDENCE}")
if(NOT DEFINED ASSET_SOURCE)
    set(ASSET_SOURCE disc)
endif()
if(ASSET_SOURCE STREQUAL "disc")
    set(mode disc)
else()
    set(mode cache)
endif()
if(NOT DEFINED ASSETS)
    set(ASSETS 88 90 92 94 96 98 100 102 104 106 108 110 112 114 116 118 120 122 124 126)
endif()
set(earlyBanks 88 90 92 96 98 100)
set(models 0 2 1 1)
foreach(asset IN LISTS ASSETS)
    math(EXPR class "(${asset}-88)/8")
    math(EXPR course "((${asset}-88)%8)/2")
    list(GET models ${course} model)
    list(FIND earlyBanks ${asset} earlyIndex)
    if(NOT earlyIndex EQUAL -1)
        set(triangles 1435)
    else()
        set(triangles 1453)
    endif()
    string(REPEAT "${model}," 10 grid)
    string(APPEND grid "${model}")
    set(log "${EVIDENCE}/esperanza-${mode}-bank-${asset}.log")
    file(REMOVE "${log}")
    execute_process(COMMAND "${GAME}" --scenario "${SOURCE}/tests/scenarios/authored_esperanza.ini"
        --set stop.timer=120 --set "race.class=${class}" --set "race.course=${course}"
        --set "race.grid=${grid}" --set "diagnostics.log=${log}" --set "modern.assets=${ASSET_SOURCE}"
        WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Esperanza bank ${asset} race failed: ${status}\n${output}\n${errors}")
    endif()
    file(READ "${log}" trace)
    foreach(index RANGE 0 2)
        if(NOT trace MATCHES "scenario-start rival=${index} [^\n]*model=${model}")
            message(FATAL_ERROR "Esperanza bank ${asset} initialized the wrong rival ${index}")
        endif()
    endforeach()
    foreach(required "authored Esperanza player body installed asset=28"
            "authored Esperanza rival body installed asset=${asset} \\(${triangles} triangles\\)")
        if(NOT trace MATCHES "${required}")
            message(FATAL_ERROR "Esperanza bank ${asset} missed ${required}")
        endif()
    endforeach()
    set(previous "")
    if(asset EQUAL 96 OR asset EQUAL 98 OR asset EQUAL 100)
        set(previous Erriso)
    elseif(asset GREATER_EQUAL 102 AND asset LESS_EQUAL 110)
        set(previous Abeille)
    elseif(asset EQUAL 94 OR asset GREATER_EQUAL 112)
        set(previous Pegase)
    endif()
    if(NOT previous STREQUAL "" AND NOT trace MATCHES "authored ${previous} rival body installed asset=${asset}")
        message(FATAL_ERROR "Esperanza replacement skipped the existing ${previous} body")
    endif()
endforeach()
