if(NOT DEFINED GAME OR NOT DEFINED SOURCE OR NOT DEFINED GENERATOR OR NOT DEFINED OUTPUT_ROOT)
    message(FATAL_ERROR "GAME, SOURCE, GENERATOR and OUTPUT_ROOT are required")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT_ROOT}/save-roundtrip-${id}")
file(MAKE_DIRECTORY "${root}")
if(APPLE)
    set(card_suffix "Library/Application Support/Rage Racer/bu00")
elseif(WIN32)
    set(card_suffix "Rage Racer/bu00")
else()
    set(card_suffix "rage-racer/bu00")
endif()
function(link_assets work)
    file(CREATE_LINK "${SOURCE}/assets" "${work}/assets" SYMBOLIC)
endfunction()
function(run_game work log_out)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "HOME=${work}" "XDG_STATE_HOME=${work}" "APPDATA=${work}" SDL_AUDIODRIVER=dummy
        ${ARGN} "${GAME}" WORKING_DIRECTORY "${work}" TIMEOUT 75
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(log "${output}${error}")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Save roundtrip game run failed (${result}) in ${work}:\n${log}")
    endif()
    set(${log_out} "${log}" PARENT_SCOPE)
endfunction()

set(work "${root}/write")
file(MAKE_DIRECTORY "${work}")
link_assets("${work}")
run_game("${work}" write_log RAGE_PORT_SMOKE_FRAMES=700 RAGE_PORT_SMOKE_SAVE_ROUNDTRIP=1
    RAGE_PORT_STATE_INPUT_SCRIPT=4@80@0:START,4@180@2:CROSS)
if(NOT write_log MATCHES "save roundtrip ok: money=123456789")
    message(FATAL_ERROR "Saved progress was not restored: ${root}")
endif()
set(card "${work}/${card_suffix}")
file(GLOB save_files LIST_DIRECTORIES false "${card}/*")
list(LENGTH save_files save_count)
if(NOT save_count EQUAL 1)
    message(FATAL_ERROR "Memory card did not contain exactly one save: ${root}")
endif()
list(GET save_files 0 save_file)
get_filename_component(save_name "${save_file}" NAME)
file(SIZE "${save_file}" save_size)
if(NOT save_name STREQUAL "BESCES-00650 RAGE000" OR NOT save_size EQUAL 4864)
    message(FATAL_ERROR "Memory-card save has the wrong retail name or size: ${save_name}, ${save_size}")
endif()

run_game("${work}" menu_log RAGE_PORT_SMOKE_FRAMES=900
    RAGE_PORT_STATE_INPUT_SCRIPT=4@80@0:START,4@170@2:DOWN,4@190@2:DOWN,4@220@2:CROSS)
foreach(required "stopped at frame 900, scene 26" "files=1 free=15 mask=1 page=0")
    string(FIND "${menu_log}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Graphical memory-card menu missed ${required}: ${root}")
    endif()
endforeach()

foreach(label existing empty)
    set(load_work "${root}/load-${label}")
    file(MAKE_DIRECTORY "${load_work}/${card_suffix}")
    link_assets("${load_work}")
    if(label STREQUAL "existing")
        file(COPY_FILE "${save_file}" "${load_work}/${card_suffix}/${save_name}")
    endif()
    run_game("${load_work}" load_log RAGE_PORT_SMOKE_FRAMES=1150
        RAGE_PORT_RAW_INPUT_SCRIPT=880:UP,900:CROSS,1050:CROSS
        RAGE_PORT_STATE_INPUT_SCRIPT=4@80@0:START,4@170@2:DOWN,4@190@2:DOWN,4@220@2:CROSS)
    if(NOT load_log MATCHES "stopped at frame 1150, scene 26")
        message(FATAL_ERROR "LOAD GAME with ${label} slot left the card menu: ${root}")
    endif()
endforeach()

set(complete_work "${root}/complete")
set(complete_card "${complete_work}/${card_suffix}")
file(MAKE_DIRECTORY "${complete_card}")
link_assets("${complete_work}")
execute_process(COMMAND "${GENERATOR}" --name UNLOCK WORKING_DIRECTORY "${complete_card}" TIMEOUT 15
    RESULT_VARIABLE generator_result OUTPUT_VARIABLE generator_output ERROR_VARIABLE generator_error)
if(NOT generator_result EQUAL 0)
    message(FATAL_ERROR "Complete save generator failed: ${generator_output}${generator_error}")
endif()
run_game("${complete_work}" complete_log RAGE_PORT_SMOKE_FRAMES=700
    RAGE_PORT_SMOKE_COMPLETE_SAVE_LOAD=1 RAGE_PORT_INPUT_SCRIPT=400:START,500:START,650:CROSS)
if(NOT complete_log MATCHES "complete generated save loaded: classes=4/5 cars=13/13/13")
    message(FATAL_ERROR "Game rejected the generated complete save: ${root}")
endif()
message(STATUS "Save roundtrip and graphical memory-card menu both succeeded")
