file(MAKE_DIRECTORY "${EVIDENCE}")
if(NOT DEFINED ASSET_SOURCE)
    set(ASSET_SOURCE disc)
endif()
if(ASSET_SOURCE STREQUAL "disc")
    set(mode disc)
else()
    set(mode cache)
endif()
foreach(asset 88 90 92 96 98 100)
    math(EXPR class "(${asset}-88)/8")
    math(EXPR course "(${asset}-88-${class}*8)/2")
    set(log "${EVIDENCE}/esperanza-duplicate-${mode}-bank-${asset}.log")
    file(REMOVE "${log}")
    execute_process(COMMAND "${GAME}" --scenario "${SOURCE}/tests/scenarios/authored_esperanza_duplicate.ini"
        --set stop.timer=120 --set "race.class=${class}" --set "race.course=${course}"
        --set "diagnostics.log=${log}" --set "modern.assets=${ASSET_SOURCE}"
        WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Esperanza duplicate bank ${asset} failed: ${status}\n${output}\n${errors}")
    endif()
    file(READ "${log}" trace)
    foreach(required "scenario-start rival=0 [^\n]*model=3"
            "authored Esperanza player body installed asset=28")
        if(NOT trace MATCHES "${required}")
            message(FATAL_ERROR "Esperanza duplicate bank ${asset} missed ${required}")
        endif()
    endforeach()
    string(REGEX MATCHALL "authored Esperanza rival body installed asset=${asset} " installed "${trace}")
    list(LENGTH installed count)
    if(class EQUAL 0)
        set(expected 4)
    else()
        set(expected 2)
    endif()
    if(NOT count EQUAL expected)
        message(FATAL_ERROR "Esperanza bank ${asset} did not install all ${expected} rival bodies")
    endif()
endforeach()
