string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(directory "${OUTPUT_ROOT}/rage restart ąę ${suffix}")
file(MAKE_DIRECTORY "${directory}")
set(scenario "${directory}/powtórne wejście.ini")
file(WRITE "${scenario}" "[race]\nenabled=true\nmode=grand-prix\nseries=gp\nclass=0\ncourse=0\ncar=3\n[run]\nframes=2520\n[hooks]\nrestart_race_frames=2300,2400\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
    "${GAME}" --scenario "${scenario}"
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 180
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(log "${output}${error}")
file(WRITE "${directory}/game.log" "${log}")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Re-entering race terminated game (${result}): ${directory}")
endif()
string(REGEX MATCHALL "smoke race restart frame=" restarts "${log}")
list(LENGTH restarts count)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Expected two race restarts, got ${count}: ${directory}")
endif()
string(REGEX MATCHALL "(^|\n)Rage Racer smoke stopped[^\r\n]*" stops "${log}")
if(NOT stops)
    message(FATAL_ERROR "Missing final smoke state: ${directory}")
endif()
list(GET stops -1 final)
string(FIND "${final}" "scene 12" position)
if(position LESS 0)
    message(FATAL_ERROR "Game did not finish in live race: ${directory}")
endif()
message(STATUS "Two live race restarts verified: ${directory}")
