#ifndef RAGE_MOD_SNAPSHOT_H
#define RAGE_MOD_SNAPSHOT_H
#include "yyjson.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <io.h>
#include <fcntl.h>
#endif

#include "render/mod_file_snapshot.h"

/* Bounded JSON array of [source,target] pairs, generated by the launcher after
 * inventory/path checks. Parents must already exist; destinations must not.
 * Caller owns the private staging tree and removes partial output on failure. */
static int SnapshotCommand(void) {
    enum { LIMIT = 8 * 1024 * 1024 };
    char *bytes = malloc(LIMIT+1u);
    yyjson_doc *doc = NULL;
    int ok = 0;
    if (!bytes) return 1;
#ifdef _WIN32
    if (_setmode(_fileno(stdin),_O_BINARY) == -1) goto done;
#endif
    size_t size = fread(bytes,1,LIMIT+1u,stdin);
    if (size > LIMIT || ferror(stdin)) goto done;
    doc = yyjson_read(bytes,size,0);
    if (!doc) goto done;
    yyjson_val *root = yyjson_doc_get_root(doc), *pair;
    if (!yyjson_is_arr(root) || yyjson_arr_size(root) > 10000) goto done;
    size_t i, count, total = 0;
    yyjson_arr_foreach(root,i,count,pair) {
        if (!yyjson_is_arr(pair) || yyjson_arr_size(pair) != 2) goto done;
        for (size_t p = 0; p < 2; ++p) {
            yyjson_val *v = yyjson_arr_get(pair,p);
            if (!yyjson_is_str(v) || !yyjson_get_len(v) ||
                strlen(yyjson_get_str(v)) != yyjson_get_len(v)) goto done;
        }
    }
    yyjson_arr_foreach(root,i,count,pair) {
        if (!ModFileSnapshotCopy(yyjson_get_str(yyjson_arr_get(pair,0)),
            yyjson_get_str(yyjson_arr_get(pair,1)),&total)) goto done;
    }
    ok = 1;
done:
    yyjson_doc_free(doc); free(bytes);
    if (!ok) fputs("Cannot snapshot mod files; source changed, limit exceeded or copy failed\n",stderr);
    return ok ? 0 : 1;
}
#endif
