# Seed prior courses, finish through lap logic, then use the real prize flow.
if(NOT DEFINED CLASS)
    set(CLASS 0)
endif()
if(NOT DEFINED SERIES)
    set(SERIES 0)
endif()
if(NOT CLASS MATCHES "^[0-4]$" OR NOT SERIES MATCHES "^[01]$" OR
   (CLASS EQUAL 4 AND SERIES EQUAL 1))
    message(FATAL_ERROR "Unsupported award fixture class/series")
endif()
math(EXPR stream "1 + ${SERIES} * 4 + ${CLASS}")
set(return_scene 7)
if(CLASS EQUAL 4)
    set(stream 10)
    set(return_scene 33)
endif()
if(NOT DEFINED EXPECT_REGION)
    set(EXPECT_REGION PAL)
endif()
if(NOT EXPECT_REGION MATCHES "^(PAL|NTSC-U|NTSC-J)$")
    message(FATAL_ERROR "Unsupported expected region")
endif()
set(disc "$ENV{${DISC_ENV}}")
if(disc STREQUAL "" AND EXPECT_REGION STREQUAL "PAL")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(EXPECT_REGION STREQUAL "PAL")
    set(timing "pal base_hz=50")
    set(frames 4200)
else()
    set(timing "ntsc base_hz=60")
    set(frames 4200)
endif()
if(stream EQUAL 10)
    set(frames 10000) # Includes 1500 ending frames and the post-race setup.
endif()
if(NOT EXISTS "${disc}")
    message("SKIP: no ${EXPECT_REGION} disc for class award FMV")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(out "${OUTPUT_ROOT}/class-award-${id}")
file(MAKE_DIRECTORY "${out}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "SDL_AUDIODRIVER=dummy" "XDG_STATE_HOME=${out}/state"
    "RAGE_PORT_FMV_TRACE=1" "RAGE_PORT_SMOKE_AUDIO_METRICS=1"
    "PSYZ_AUDIO_PCM_DUMP=${out}/audio.s16le"
    "${GAME}" --scenario "${SOURCE}/race-scenario.ini"
    --set "disc.image=${disc}" --set video.renderer=modern
    --set "race.class=${CLASS}" --set race.course=0 --set "race.series=${SERIES}"
    --set "run.frames=${frames}" --set hooks.finish_frame=500
    --set hooks.auto_confirm_frame=800 --set hooks.prior_course_wins=true
    --set hooks.preserve_fmv=true --set race.after_finish=repeat
    --set diagnostics.marker_capture=false --set diagnostics.marker_history=false
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 120 RESULT_VARIABLE result
    OUTPUT_FILE "${out}/game.log" ERROR_FILE "${out}/game.log")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Class award run failed: ${out}")
endif()
file(READ "${out}/game.log" log)
foreach(required "prior course wins seeded class=${CLASS} course=0" "native GPU pipeline ready"
                 "region=${EXPECT_REGION}" "timing=${timing}")
    if(NOT log MATCHES "${required}")
        message(FATAL_ERROR "Missing ${required}: ${out}")
    endif()
endforeach()
string(FIND "${log}" "scenario race finished after_finish=repeat" finish)
if(finish LESS 0)
    message(FATAL_ERROR "Race did not finish: ${out}")
endif()
string(SUBSTRING "${log}" ${finish} -1 award)
foreach(required "scene=19 " "scene=5 " "scene=${return_scene} " "fmv xa start:" "fmv xa end")
    if(NOT award MATCHES "${required}")
        message(FATAL_ERROR "Missing award transition ${required}: ${out}")
    endif()
endforeach()
if(NOT award MATCHES "fmv xa mixer energy=([0-9]+)" OR CMAKE_MATCH_1 LESS_EQUAL 0)
    message(FATAL_ERROR "Award XA made no contribution to the mixer: ${out}")
endif()
file(WRITE "${out}/award.log" "timing=${timing}\n${award}")
execute_process(COMMAND "${PACING_CHECK}" "${disc}" "${stream}" "${out}/award.log"
    RESULT_VARIABLE result OUTPUT_VARIABLE pacing ERROR_VARIABLE error)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Award movie timing/frames failed: ${pacing}${error}; ${out}")
endif()
if(NOT log MATCHES "audio metrics: frames=([0-9]+) energy=([0-9]+)")
    message(FATAL_ERROR "Missing session PCM metrics: ${out}")
endif()
execute_process(COMMAND "${PCM_CHECK}" "${out}/audio.s16le" "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}"
    RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Session PCM failed: ${out}")
endif()
message(STATUS "Class award FMV passed: ${out}; ${pacing}")
