set(disc "$ENV{RAGE_PORT_DISC_IMAGE}")
if(disc STREQUAL "")
    set(disc "$ENV{RAGE_PORT_DISC_CUE}")
endif()
if(disc STREQUAL "")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(NOT EXISTS "${disc}" OR IS_DIRECTORY "${disc}")
    message("SKIP: no disc image for in-process FMV playback")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${OUTPUT_ROOT}/rage fmv ąę ${suffix}")
set(empty_path "${root}/pusta ścieżka")
set(temporary "${root}/pliki tymczasowe żółte")
file(MAKE_DIRECTORY "${empty_path}" "${temporary}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    SDL_AUDIODRIVER=dummy "PATH=${empty_path}" "TMPDIR=${temporary}"
    RAGE_PORT_SMOKE_FRAMES=380 RAGE_PORT_FMV_TRACE=1
    "${GAME}" --set "disc.image=${disc}"
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 75
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(log "${output}${error}")
file(WRITE "${root}/game.log" "${log}")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "In-process FMV terminated the game (${result}): ${root}")
endif()
string(FIND "${log}" "fmv frame=" frame_position)
if(frame_position LESS 0)
    message(FATAL_ERROR "In-process FMV was not observable: ${root}")
endif()
file(GLOB leftovers LIST_DIRECTORIES true "${temporary}/*" "${temporary}/.[!.]*" "${temporary}/..?*")
if(leftovers)
    message(FATAL_ERROR "FMV temporary files leaked: ${leftovers}")
endif()
message(STATUS "In-process FMV without PATH tools passed: ${root}")
