if(NOT DEFINED GAME OR NOT DEFINED SOURCE OR NOT DEFINED OUTPUT_ROOT OR
   NOT DEFINED PCM_CHECK OR NOT DEFINED PPM_CHECK)
    message(FATAL_ERROR "GAME, SOURCE, OUTPUT_ROOT, PCM_CHECK and PPM_CHECK are required")
endif()
set(disc "$ENV{RAGE_PORT_DISC_IMAGE}")
if(disc STREQUAL "")
    set(disc "$ENV{RAGE_PORT_DISC_CUE}")
endif()
if(disc STREQUAL "")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(NOT EXISTS "${disc}" OR IS_DIRECTORY "${disc}")
    message("SKIP: no disc image for FMV frame layout")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT_ROOT}/fmv-frame-${id}")
file(MAKE_DIRECTORY "${root}")
set(capture "${root}/fmv.ppm")
set(pcm "${root}/fmv-s16le-stereo.pcm")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
    RAGE_PORT_SMOKE_FRAMES=720 "RAGE_PORT_CAPTURE_PATH=${capture}"
    RAGE_PORT_FMV_TRACE=1 RAGE_PORT_SMOKE_AUDIO_METRICS=1 "PSYZ_AUDIO_PCM_DUMP=${pcm}"
    "${GAME}" --set "disc.image=${disc}" --set timing.standard=ntsc --set video.renderer=classic
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 60 RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(log "${output}${error}")
file(WRITE "${root}/game.log" "${log}")
if(NOT result EQUAL 0 OR NOT EXISTS "${capture}" OR NOT EXISTS "${pcm}")
    message(FATAL_ERROR "FMV frame-layout run failed: ${root}")
endif()
string(FIND "${log}" "fmv frame=" frame_position)
if(frame_position LESS 0)
    message(FATAL_ERROR "Intro FMV decoded no frame: ${root}")
endif()
string(REGEX MATCH "audio metrics: frames=([0-9]+) energy=([0-9]+)" metrics "${log}")
if(NOT metrics OR CMAKE_MATCH_1 LESS 10000 OR CMAKE_MATCH_2 EQUAL 0)
    message(FATAL_ERROR "Intro FMV reported invalid audio metrics: ${root}")
endif()
execute_process(COMMAND "${PCM_CHECK}" "${pcm}" "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}"
    RESULT_VARIABLE pcm_result OUTPUT_VARIABLE pcm_output ERROR_VARIABLE pcm_error)
file(WRITE "${root}/pcm-check.log" "${pcm_output}${pcm_error}")
if(NOT pcm_result EQUAL 0)
    message(FATAL_ERROR "FMV PCM is invalid: ${root}")
endif()
execute_process(COMMAND "${PPM_CHECK}" fmv "${capture}" RESULT_VARIABLE image_result)
if(NOT image_result EQUAL 0)
    message(FATAL_ERROR "FMV frame layout is invalid: ${root}")
endif()
message(STATUS "FMV picture is centered, decoded and free of colour corruption: ${root}")
