if(NOT DEFINED GAME OR NOT DEFINED SOURCE OR NOT DEFINED OUTPUT_ROOT OR
   NOT DEFINED PCM_CHECK OR NOT DEFINED PACING_CHECK)
    message(FATAL_ERROR "GAME, SOURCE, OUTPUT_ROOT, PCM_CHECK and PACING_CHECK are required")
endif()
set(disc "$ENV{RAGE_PORT_DISC_IMAGE}")
if(disc STREQUAL "")
    set(disc "$ENV{RAGE_PORT_DISC_CUE}")
endif()
if(disc STREQUAL "")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
get_filename_component(extension "${disc}" LAST_EXT)
string(TOLOWER "${extension}" extension)
if(NOT EXISTS "${disc}" OR IS_DIRECTORY "${disc}" OR extension STREQUAL ".chd")
    message("SKIP: FMV pacing needs a readable CUE or BIN disc image")
    return()
endif()
if(ALL_AUDIO)
    set(streams 0 1 2 3 4 5 6 7 8 9 10)
else()
    set(streams 5 0)
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT_ROOT}/fmv-pacing-${id}")
file(MAKE_DIRECTORY "${root}")
foreach(stream IN LISTS streams)
    set(smoke_frames 2100)
    if(stream EQUAL 0)
        set(smoke_frames 9540)
    elseif(stream EQUAL 10)
        set(smoke_frames 6900)
    endif()
    set(pcm "${root}/stream-${stream}.s16le")
    set(log "${root}/stream-${stream}.log")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
        "RAGE_PORT_SMOKE_FRAMES=${smoke_frames}" RAGE_PORT_FMV_TRACE=1
        RAGE_PORT_SMOKE_AUDIO_METRICS=1 "PSYZ_AUDIO_PCM_DUMP=${pcm}"
        "${GAME}" --set "disc.image=${disc}" --set "diagnostics.fmv_stream=${stream}"
        --set video.renderer=classic WORKING_DIRECTORY "${SOURCE}" TIMEOUT 540
        RESULT_VARIABLE result OUTPUT_FILE "${log}" ERROR_FILE "${log}")
    if(NOT result EQUAL 0 OR NOT EXISTS "${pcm}")
        message(FATAL_ERROR "FMV stream ${stream} failed: ${root}")
    endif()
    file(READ "${log}" text)
    if(NOT text MATCHES "fmv xa start" OR
       NOT text MATCHES "audio metrics: frames=([0-9]+) energy=([0-9]+)")
        message(FATAL_ERROR "FMV stream ${stream} emitted no decoded sound: ${root}")
    endif()
    set(audio_frames "${CMAKE_MATCH_1}")
    set(audio_energy "${CMAKE_MATCH_2}")
    if(audio_frames LESS 10000 OR audio_energy EQUAL 0)
        message(FATAL_ERROR "FMV stream ${stream} audio metrics are invalid: ${root}")
    endif()
    execute_process(COMMAND "${PCM_CHECK}" "${pcm}" "${audio_frames}" "${audio_energy}"
        RESULT_VARIABLE pcm_result OUTPUT_VARIABLE pcm_output ERROR_VARIABLE pcm_error)
    file(WRITE "${root}/stream-${stream}-pcm.log" "${pcm_output}${pcm_error}")
    if(NOT pcm_result EQUAL 0)
        message(FATAL_ERROR "FMV stream ${stream} PCM mismatch: ${root}")
    endif()
    set(strict)
    if(NOT ALL_AUDIO)
        set(strict --strict-audio)
        if(NOT text MATCHES "fmv video end: xa tail continues")
            message(FATAL_ERROR "FMV stream ${stream} cut XA at its last picture: ${root}")
        endif()
    endif()
    execute_process(COMMAND "${PACING_CHECK}" "${disc}" "${stream}" "${log}" ${strict}
        RESULT_VARIABLE pacing_result OUTPUT_VARIABLE pacing_output ERROR_VARIABLE pacing_error)
    file(WRITE "${root}/stream-${stream}-pacing.log" "${pacing_output}${pacing_error}")
    if(NOT pacing_result EQUAL 0)
        message(FATAL_ERROR "FMV stream ${stream} sector/XA pacing mismatch: ${root}")
    endif()
endforeach()
if(ALL_AUDIO)
    message(STATUS "Every retail FMV fully decoded and emitted non-silent PCM")
else()
    message(STATUS "Representative movies matched their XA soundtrack duration")
endif()
