if(NOT DEFINED GAME OR NOT DEFINED SOURCE)
    message(FATAL_ERROR "GAME and SOURCE are required")
endif()
set(disc "$ENV{RAGE_PORT_DISC_IMAGE}")
if(disc STREQUAL "")
    set(disc "$ENV{RAGE_PORT_DISC_CUE}")
endif()
if(disc STREQUAL "")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(NOT EXISTS "${disc}" OR IS_DIRECTORY "${disc}")
    message("SKIP: no disc image for race CD-DA")
    return()
endif()
set(route 400:START,500:START,650:CROSS,950:CROSS,1100:CROSS,1200:CROSS)
execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
    RAGE_PORT_SMOKE_FRAMES=1800 RAGE_PORT_SMOKE_AUDIO_METRICS=1 "RAGE_PORT_INPUT_SCRIPT=${route}"
    "${GAME}" --set "disc.image=${disc}" WORKING_DIRECTORY "${SOURCE}" TIMEOUT 120
    RESULT_VARIABLE race_result OUTPUT_VARIABLE race_output ERROR_VARIABLE race_error)
set(race_log "${race_output}${race_error}")
if(NOT race_result EQUAL 0)
    message(FATAL_ERROR "Race CD-DA run failed (${race_result}):\n${race_log}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
    RAGE_PORT_SMOKE_FRAMES=1200 RAGE_PORT_SMOKE_AUDIO_METRICS=1
    RAGE_PORT_INPUT_SCRIPT=400:START,500:START
    "${GAME}" --set "disc.image=${disc}" WORKING_DIRECTORY "${SOURCE}" TIMEOUT 120
    RESULT_VARIABLE prologue_result OUTPUT_VARIABLE prologue_output ERROR_VARIABLE prologue_error)
set(prologue_log "${prologue_output}${prologue_error}")
if(NOT prologue_result EQUAL 0)
    message(FATAL_ERROR "Prologue CD-DA run failed (${prologue_result}):\n${prologue_log}")
endif()
if(NOT prologue_log MATCHES "stopped at frame 1200, scene 32" OR
   NOT prologue_log MATCHES "cdda_frames=([1-9][0-9]*) cdda_energy=([1-9][0-9]*) cdda_mix_energy=([1-9][0-9]*)")
    message(FATAL_ERROR "Grand Prix prologue CD-DA produced no mixed sound")
endif()
string(REGEX MATCHALL "opened (track .*\\(Track [0-9]+\\)\\.bin|virtual track [0-9]+)" track_entries "${race_log}")
list(LENGTH track_entries track_count)
if(track_count LESS 2)
    message(FATAL_ERROR "Race did not report enough disc-track transitions")
endif()
list(GET track_entries 0 first_track_entry)
list(GET track_entries -1 last_track_entry)
string(REGEX MATCH "[0-9]+" first_track_number "${first_track_entry}")
set(first_track "${CMAKE_MATCH_0}")
string(REGEX MATCH "[0-9]+" last_track_number "${last_track_entry}")
set(last_track "${CMAKE_MATCH_0}")
if(NOT first_track EQUAL 1 OR last_track LESS_EQUAL 2)
    message(FATAL_ERROR "Race did not switch from prologue XA to race CD-DA: first=${first_track}, last=${last_track}")
endif()
if(NOT race_log MATCHES "stopped at frame 1800, scene 12" OR
   NOT race_log MATCHES "cdda_frames=([1-9][0-9]*) cdda_energy=([1-9][0-9]*) cdda_mix_energy=([1-9][0-9]*)")
    message(FATAL_ERROR "Race CD-DA track opened but produced no mixed sound")
endif()
message(STATUS "Audio switched from intro XA to race CD-DA track ${last_track}")
