string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT}/żółte dane ${id}")
file(MAKE_DIRECTORY "${root}")
execute_process(COMMAND "${TOOL}" "${root}" RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Fixture generation failed: ${root}")
endif()
file(SIZE "${root}/car.rmesh" size)
if(NOT size EQUAL 139292)
    message(FATAL_ERROR "Wrong mesh size: ${size}")
endif()
file(SIZE "${root}/material.rgba" size)
if(NOT size EQUAL 262144)
    message(FATAL_ERROR "Wrong RGBA size")
endif()
file(SIZE "${root}/material.rpaint" size)
if(NOT size EQUAL 65536)
    message(FATAL_ERROR "Wrong paint size")
endif()
file(READ "${root}/terrain.png" signature LIMIT 24 HEX)
if(NOT signature STREQUAL "89504e470d0a1a0a0000000d494844520000004000000020")
    message(FATAL_ERROR "Wrong PNG signature or dimensions: ${signature}")
endif()
file(SHA256 "${root}/car.rmesh" before)
execute_process(COMMAND "${TOOL}" "${root}" RESULT_VARIABLE result)
file(SHA256 "${root}/car.rmesh" after)
if(result STREQUAL "0" OR NOT before STREQUAL after)
    message(FATAL_ERROR "Existing fixture was overwritten")
endif()
