#include "client_race.h"
#include <stdio.h>
#include <string.h>
#define CHECK(c) do { if (!(c)) { fprintf(stderr, "line %d: %s\n", __LINE__, #c); return 1; } } while (0)
static int TestEnvironmentClock(void) {
    struct { u32 skyRowBase, length; struct GameEnvironmentCue cues[3]; } script = {
        .length = 30, .cues = {{.time = 0, .duration = 4},
            {.time = 15, .duration = 6, .mode = 2}, {.time = -1}}};
    script.cues[0].colors[ENV_FOG].bytes.r = 12;
    script.cues[1].colors[ENV_FOG].bytes.r = 120;
    EnvironmentPalette palettes[ENVIRONMENT_PALETTE_COUNT] = {0};
    ClientRace race = {0};
    CHECK(InitEnvironment(&race.env, (const void *)&script, sizeof(script), palettes, 0));
    Environment expected = race.env;
    const RaceSim untouched = race.sim;
    race.sim.tick = 1;
    CHECK(TickClientScenery(&race));
    CHECK(memcmp(&race.env, &expected, sizeof(expected)) == 0);
    race.sim.tick = 500;
    for (int tick = 0; tick < 250; ++tick) CHECK(TickEnvironment(&expected));
    CHECK(TickClientScenery(&race));
    CHECK(memcmp(&race.env, &expected, sizeof(expected)) == 0);
    RaceSim sim = untouched;
    sim.tick = 500;
    CHECK(memcmp(&race.sim, &sim, sizeof(sim)) == 0);
    CHECK(TickClientScenery(&race));
    CHECK(memcmp(&race.env, &expected, sizeof(expected)) == 0);
    race.env.enabled = 0;
    Environment disabled = race.env;
    race.sim.tick += 2;
    CHECK(TickClientScenery(&race));
    CHECK(memcmp(&race.env, &disabled, sizeof(disabled)) == 0);
    race.env.enabled = 1;
    race.env.mode = ENVIRONMENT_PALETTE_COUNT;
    ClientRace before = race;
    race.sim.tick += 2;
    before.sim.tick = race.sim.tick;
    CHECK(!TickClientScenery(&race));
    CHECK(memcmp(&race, &before, sizeof(race)) == 0);
    return 0;
}

int main(void) {
    CHECK(TestEnvironmentClock() == 0);
    u16 grid[1024];
    u32 visibility[32][32] = {{0}};
    for (unsigned i = 0; i < 1024; ++i) grid[i] = 0x3ff;
    grid[31 * 32] = 0;
    grid[31 * 32 + 1] = 1;
    visibility[0][0] = 1;
    ClientRace race = {.terrain = {.cellCount = 2, .grid = grid, .visibility = visibility}};
    race.terrainMesh.cached.assetKey = 88;
    RenderMeshInstance storage[4] = {{0}}, otherStorage[4] = {{0}};
    RenderWorld world, other;
    RenderWorldInit(&world, storage, 4);
    world.hasCamera = 1;
    world.camera.transform.position = (Vec3){1024, 0, -1024};
    storage[0].assetSet = RAGE_RENDER_ASSET_MODEL_BANK;
    world.instanceCount = 1;
    CHECK(SubmitClientTerrain(&race, 0, &world));
    CHECK(world.instanceCount == 3 && storage[0].assetSet == RAGE_RENDER_ASSET_MODEL_BANK);
    CHECK(storage[1].entity == 0x20000 && storage[1].mesh == 0);
    CHECK(storage[1].transform.position.x == 1024 && storage[1].transform.position.z == -1024);
    CHECK(storage[1].assetSource == RENDER_ASSET_OWNED && storage[1].assetKey == 88);
    CHECK(!(storage[1].flags & RAGE_RENDER_INSTANCE_RAY_ONLY));
    CHECK(storage[2].flags & RAGE_RENDER_INSTANCE_RAY_ONLY);
    CHECK(storage[2].transform.position.x == 3072);
    const RenderWorld saved = world;
    RenderMeshInstance savedStorage[4];
    memcpy(savedStorage, storage, sizeof(storage));
    CHECK(SubmitClientTerrain(&race, 0, &world));
    CHECK(memcmp(storage, savedStorage, sizeof(storage)) == 0);
    CHECK(world.instanceCount == 3);
    /* A texture bank replaces the same cells, rather than adding another terrain. */
    CHECK(SubmitClientTerrain(&race, 1, &world));
    CHECK(world.instanceCount == 3);
    CHECK(storage[0].assetSet == RAGE_RENDER_ASSET_MODEL_BANK);
    CHECK(storage[1].materialVariant == 2 && storage[2].materialVariant == 2);
    CHECK(storage[1].entity == savedStorage[1].entity && storage[2].entity == savedStorage[2].entity);
    CHECK(SubmitClientTerrain(&race, 0, &world));
    CHECK(memcmp(storage, savedStorage, sizeof(storage)) == 0);

    grid[0] = 2;
    CHECK(!SubmitClientTerrain(&race, 0, &world));
    CHECK(memcmp(&saved, &world, sizeof(world)) == 0);
    CHECK(memcmp(storage, savedStorage, sizeof(storage)) == 0);
    grid[0] = 0x3ff;
    race.terrain.cellCount = GAME_TERRAIN_CELL_LIMIT + 1;
    CHECK(!SubmitClientTerrain(&race, 0, &world));
    CHECK(memcmp(&saved, &world, sizeof(world)) == 0);
    race.terrain.cellCount = 2;
    CHECK(!SubmitClientTerrain(&race, 2, &world));
    CHECK(!SubmitClientTerrain(NULL, 0, &world));
    world.instanceCount = 1;
    world.instanceCapacity = 2;
    const RenderWorld full = world;
    CHECK(!SubmitClientTerrain(&race, 0, &world));
    CHECK(memcmp(storage, savedStorage, sizeof(storage)) == 0);
    CHECK(memcmp(&full, &world, sizeof(world)) == 0);
    world.instanceCapacity = 4;
    world.instanceCount = 3;
    RenderWorldInit(&other, otherStorage, 4);
    race.env.mode4 = 1;
    CHECK(SubmitClientTerrain(&race, 1, &other));
    CHECK(other.instanceCount == 2 && otherStorage[0].materialVariant == 3);
    CHECK(otherStorage[0].flags & RAGE_RENDER_INSTANCE_ENVIRONMENT_MODE_4);
    CHECK(!(otherStorage[1].flags & RAGE_RENDER_INSTANCE_RAY_ONLY));
    CHECK(memcmp(&saved, &world, sizeof(world)) == 0);
    CHECK(memcmp(storage, savedStorage, sizeof(storage)) == 0);
    CourseObject objects[] = {{.modelId = 0, .x = 1024, .z = 1024,
        .flags = COURSE_OBJECT_ALTERNATE_ENVIRONMENT_4}, {.modelId = -1}};
    race.objects = (CourseObjects){objects, 2};
    race.course.modelCount = 1;
    race.courseMesh.cached.assetKey = 88;
    CHECK(SubmitClientScenery(&race, 1, &world));
    CHECK(world.instanceCount == 4 && storage[3].entity == 0x10000);
    CHECK(storage[3].transform.position.x == 1024 && storage[3].transform.position.z == -1024);
    CHECK(storage[3].transform.hasOrientation && storage[3].materialVariant == 4);
    CHECK(storage[3].flags & RAGE_RENDER_INSTANCE_ENABLE_FOG);
    CHECK(SubmitClientScenery(&race, 1, &world) && world.instanceCount == 4);
    const RenderWorld sceneryWorld = world;
    memcpy(savedStorage, storage, sizeof(storage));
    objects[1].modelId = 1;
    CHECK(!SubmitClientScenery(&race, 0, &world));
    CHECK(memcmp(&sceneryWorld, &world, sizeof(world)) == 0);
    CHECK(memcmp(savedStorage, storage, sizeof(storage)) == 0);
    objects[1].modelId = -1;
    CHECK(!SubmitClientScenery(&race, 0, &other)); /* No camera. */
    CHECK(!SubmitClientScenery(&race, -1, &world));
    CHECK(memcmp(savedStorage, storage, sizeof(storage)) == 0);
    race.spinningScenery = 1;
    race.spinners = (Spinners){{0, 64, 128, 256}, {32, 64}};
    race.sim.drivers[0].random = 7;
    race.shuttleCount = 2;
    for (u32 i = 0; i < 2; ++i) {
        CHECK(RetailShuttle((s32)i, &race.shuttlePaths[i]));
        const ShuttleConfig *config = &race.shuttlePaths[i];
        CHECK(InitShuttle(&race.shuttles[i], &config->path, &config->angles, (s32)i, config->dwell));
    }
    CHECK(TickClientScenery(&race));
    GameShuttleScenery old[2];
    memcpy(old, race.shuttles, sizeof(old));
    race.sim.tick = 1;
    CHECK(TickClientScenery(&race));
    CHECK(race.sceneryTick == 1 && race.shuttles[0].travelStep == 1);
    CHECK(race.spinners.angles[0] == 32 && race.previousSpinners.angles[0] == 0);
    CHECK(race.sim.drivers[0].random == 7);
    CHECK(memcmp(old, race.previousShuttles, sizeof(old)) == 0);
    memcpy(old, race.shuttles, sizeof(old));
    CHECK(TickClientScenery(&race));
    CHECK(memcmp(old, race.shuttles, sizeof(old)) == 0);
    race.sim.tick = CLIENT_SCENERY_CATCHUP_LIMIT + 2;
    CHECK(!TickClientScenery(&race) && race.sceneryTick == 1);
    CHECK(memcmp(old, race.shuttles, sizeof(old)) == 0);
    race.sim.tick = 2;
    const Spinners savedSpinners = race.spinners;
    const s32 travel = race.shuttlePaths[1].travel;
    race.shuttlePaths[1].travel = 0;
    CHECK(!TickClientScenery(&race) && race.sceneryTick == 1);
    CHECK(memcmp(old, race.shuttles, sizeof(old)) == 0);
    CHECK(memcmp(&savedSpinners, &race.spinners, sizeof(savedSpinners)) == 0);
    race.shuttlePaths[1].travel = travel;
    race.freezeScenery = 1;
    CHECK(TickClientScenery(&race) && race.sceneryTick == 2);
    CHECK(memcmp(old, race.shuttles, sizeof(old)) == 0);
    CHECK(memcmp(&savedSpinners, &race.spinners, sizeof(savedSpinners)) == 0);
    race.sceneryTick = UINT32_MAX;
    race.sim.tick = 0;
    race.freezeScenery = 0;
    CHECK(TickClientScenery(&race) && race.sceneryTick == 0);
    CHECK(race.shuttles[0].travelStep == old[0].travelStep + 1);
    ClientRace sequential = race, skipped = race;
    sequential.sceneryTick = skipped.sceneryTick = 500;
    sequential.sim.tick = skipped.sim.tick = 500;
    for (u32 tick = 1; tick <= CLIENT_SCENERY_CATCHUP_LIMIT; ++tick) {
        sequential.sim.tick = 500 + tick;
        CHECK(TickClientScenery(&sequential));
    }
    skipped.sim.tick = 500 + CLIENT_SCENERY_CATCHUP_LIMIT;
    CHECK(TickClientScenery(&skipped));
    CHECK(memcmp(&sequential, &skipped, sizeof(skipped)) == 0);
    ClientRace savedRace = skipped;
    skipped.sim.tick--;
    savedRace.sim.tick = skipped.sim.tick;
    CHECK(!TickClientScenery(&skipped));
    CHECK(memcmp(&skipped, &savedRace, sizeof(savedRace)) == 0);

    RenderMeshInstance moving[3] = {{0}};
    RenderWorld movingWorld;
    RenderWorldInit(&movingWorld, moving, 3);
    movingWorld.hasCamera = 1;
    movingWorld.instanceCount = 1;
    moving[0].assetSet = RAGE_RENDER_ASSET_TERRAIN;
    moving[0].assetSource = RENDER_ASSET_OWNED;
    moving[0].entity = 0x20000;
    race.course.modelCount = 64;
    race.shuttles[0].position = (Vec4){100, 200, 300, 0};
    race.previousShuttles[0].position = (Vec4){90, 190, 290, 0};
    const u32 clock = race.sceneryTick;
    CHECK(SubmitClientShuttles(&race, 1, &movingWorld));
    CHECK(movingWorld.instanceCount == 3 && moving[1].entity == 0x30110);
    CHECK(moving[0].assetSet == RAGE_RENDER_ASSET_TERRAIN && moving[0].entity == 0x20000);
    CHECK(moving[1].mesh == 63 && moving[2].mesh == 60);
    CHECK(moving[1].transform.position.x == 100 && moving[1].transform.position.y == -200);
    CHECK(moving[1].previousTransform.position.x == 90);
    CHECK(moving[1].materialVariant == 4 && moving[1].assetSource == RENDER_ASSET_OWNED);
    CHECK(race.sceneryTick == clock);
    RenderMeshInstance before[3];
    memcpy(before, moving, sizeof(before));
    CHECK(SubmitClientShuttles(&race, 1, &movingWorld));
    CHECK(memcmp(before, moving, sizeof(before)) == 0);
    const RenderWorld beforeWorld = movingWorld;
    race.shuttles[1].pathIndex = -1;
    CHECK(!SubmitClientShuttles(&race, 0, &movingWorld));
    CHECK(memcmp(before, moving, sizeof(before)) == 0);
    CHECK(memcmp(&beforeWorld, &movingWorld, sizeof(beforeWorld)) == 0);
    race.shuttles[1].pathIndex = 1;
    race.course.modelCount = 1;
    CHECK(!SubmitClientShuttles(&race, 0, &movingWorld));
    CHECK(memcmp(before, moving, sizeof(before)) == 0);
    race.course.modelCount = 64;
    for (s32 i = 0; i < 4; ++i) CHECK(RetailSpinner(i, &race.spinnerPlacements[i]));
    RenderMeshInstance decorations[8] = {{0}};
    memcpy(decorations, moving, sizeof(moving));
    RenderWorld decorationsWorld;
    RenderWorldInit(&decorationsWorld, decorations, 8);
    decorationsWorld.hasCamera = 1;
    decorationsWorld.instanceCount = 3;
    CHECK(SubmitClientSpinners(&race, 1, &decorationsWorld));
    CHECK(decorationsWorld.instanceCount == 4 && decorations[3].entity == 0x30100);
    CHECK(decorations[3].mesh == 62 && decorations[3].materialVariant == 4);
    CHECK(decorations[3].flags & RAGE_RENDER_INSTANCE_ENABLE_FOG);
    CHECK(decorations[3].transform.position.x == 17805);
    CHECK(memcmp(moving, decorations, sizeof(moving)) == 0);
    CHECK(memcmp(&decorations[3].transform.orientation,
                  &decorations[3].previousTransform.orientation, sizeof(Quaternion)) != 0);
    const Spinners published = race.spinners;
    CHECK(SubmitClientSpinners(&race, 1, &decorationsWorld));
    CHECK(decorationsWorld.instanceCount == 4);
    CHECK(memcmp(&published, &race.spinners, sizeof(published)) == 0);
    race.spinningScenery = 2;
    CHECK(SubmitClientSpinners(&race, 0, &decorationsWorld));
    CHECK(decorationsWorld.instanceCount == 6 && decorations[3].entity == 0x30101);
    CHECK(decorations[5].entity == 0x30103);
    race.spinningScenery = 0;
    CHECK(SubmitClientSpinners(&race, 0, &decorationsWorld));
    CHECK(decorationsWorld.instanceCount == 3);
    CHECK(memcmp(moving, decorations, sizeof(moving)) == 0);
    race.landmarks = (StaticSceneryState){{{100, 200, 300}, 0}, {{400, 500, 600}, 1024}};
    race.highLandmark = 1;
    race.ovalLandmark = 1;
    CHECK(SubmitClientLandmarks(&race, 1, &decorationsWorld));
    CHECK(decorationsWorld.instanceCount == 5 && decorations[3].entity == 0x30000);
    CHECK(decorations[3].mesh == 58 && decorations[4].mesh == 63);
    CHECK(decorations[3].transform.position.z == -(300 + 0x5000));
    CHECK(decorations[3].materialVariant == 4 && decorations[4].materialVariant == 5);
    CHECK(!(decorations[3].flags & RAGE_RENDER_INSTANCE_ENABLE_FOG));
    CHECK(memcmp(moving, decorations, sizeof(moving)) == 0);
    race.env.mode4 = 0;
    race.highLandmark = 0;
    CHECK(SubmitClientLandmarks(&race, 0, &decorationsWorld));
    CHECK(decorationsWorld.instanceCount == 4 && decorations[3].mesh == 57);
    CHECK(decorations[3].flags & RAGE_RENDER_INSTANCE_ENABLE_FOG);
    RenderMeshInstance landmarkSaved[8];
    memcpy(landmarkSaved, decorations, sizeof(decorations));
    race.highLandmark = 1;
    decorationsWorld.instanceCapacity = 4;
    const RenderWorld landmarkWorld = decorationsWorld;
    CHECK(!SubmitClientLandmarks(&race, 0, &decorationsWorld));
    CHECK(memcmp(&landmarkWorld, &decorationsWorld, sizeof(landmarkWorld)) == 0);
    CHECK(memcmp(landmarkSaved, decorations, sizeof(decorations)) == 0);
    return 0;
}
