include("${CMAKE_CURRENT_LIST_DIR}/../../tools/verify_route_completion.cmake")
set(log "scenario repeat entered next race via menus\nautopilot result=complete races=2\n")
if(CASE STREQUAL "wrong_count")
    string(REPLACE "races=2" "races=20" log "${log}")
elseif(CASE STREQUAL "missing_menu")
    set(log "autopilot result=complete races=2\n")
elseif(CASE STREQUAL "failed")
    string(APPEND log "autopilot result=failed frame limit\n")
elseif(CASE STREQUAL "incomplete_world")
    string(APPEND log "rage-port: incomplete native world at frame 10; legacy fallback disabled\n")
elseif(NOT CASE STREQUAL "valid")
    message(FATAL_ERROR "Unknown fixture")
endif()
rage_verify_route_completion("${log}" "races=2" 2)
