# Same-process race/reward/repeat regression using the compiled route driver.
if(NOT DEFINED DISC_ENV OR NOT DEFINED EXPECT_REGION OR
   NOT EXPECT_REGION MATCHES "^(PAL|NTSC-U|NTSC-J)$")
    message(FATAL_ERROR "Regional race test requires DISC_ENV and EXPECT_REGION")
endif()
set(DISC "$ENV{${DISC_ENV}}")
if(DISC STREQUAL "" AND EXPECT_REGION STREQUAL "PAL")
    set(DISC "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(NOT EXISTS "${DISC}")
    message("SKIP: no disc for ${EXPECT_REGION} repeated races")
    return()
endif()
set(CONFIG "${SOURCE}/rage-port.ini")
set(RACES 2)
set(CLASS 1)
set(COURSE 0)
set(RESTARTS 3)
set(VERIFY_VRAM ON)
set(VERIFY_LIFECYCLE ON)
set(OUTPUT "${OUTPUT_ROOT}/regional-races")
include("${SOURCE}/tools/performance_drive.cmake")
