# A colocated, syntactically valid cache must not override the selected disc.
if(NOT DEFINED EXPECT_REGION)
    set(EXPECT_REGION PAL)
endif()
if(NOT EXPECT_REGION MATCHES "^(PAL|NTSC-U|NTSC-J)$")
    message(FATAL_ERROR "Unsupported expected region")
endif()
set(disc "$ENV{${DISC_ENV}}")
if(disc STREQUAL "" AND EXPECT_REGION STREQUAL "PAL")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(NOT EXISTS "${disc}")
    message("SKIP: default disc source requires local ${EXPECT_REGION} disc")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${OUTPUT_ROOT}/default-disc-source-${suffix}")
file(MAKE_DIRECTORY "${root}/native-assets")
get_filename_component(name "${GAME}" NAME)
file(COPY "${GAME}" DESTINATION "${root}")
file(WRITE "${root}/native-assets/runtime-index.txt"
    "# rage-rmesh-index v2\n10 model missing.rmesh missing.rmat\n")
file(WRITE "${root}/config.ini" "[video]\nrenderer=modern\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    --unset=RAGE_PORT_MODERN_ASSETS "XDG_STATE_HOME=${root}/state"
    "${root}/${name}" --config "${root}/config.ini"
    --scenario "${SOURCE}/race-scenario.ini"
    --set "disc.image=${disc}" --set run.frames=900
    --set stop.scene=12 --set stop.timer=20
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 100
    RESULT_VARIABLE result OUTPUT_FILE "${root}/stdout.log"
    ERROR_FILE "${root}/stderr.log")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Default disc source run failed: ${result}; ${root}")
endif()
file(READ "${root}/stderr.log" log)
if(NOT log MATCHES "native assets generated by C importer" OR
   log MATCHES "native asset cache " OR
   NOT log MATCHES "native GPU pipeline ready")
    message(FATAL_ERROR "Colocated cache shadowed selected disc: ${root}")
endif()
if(EXPECT_REGION STREQUAL "PAL")
    set(timing "pal base_hz=50")
else()
    set(timing "ntsc base_hz=60")
endif()
if(NOT log MATCHES "disc [^\r\n]+ region=${EXPECT_REGION}[\r\n]" OR
   NOT log MATCHES "timing standard selected from disc region=${EXPECT_REGION}[\r\n]" OR
   NOT log MATCHES "timing=${timing}[\r\n]")
    message(FATAL_ERROR "Selected disc region/timing mismatch: ${root}")
endif()
message(STATUS "Default disc source verified: ${root}")
