# A colocated, syntactically valid cache must not override the selected disc.
set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
if(NOT EXISTS "${disc}")
    message("SKIP: default disc source requires local PAL disc")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${OUTPUT_ROOT}/default-disc-source-${suffix}")
file(MAKE_DIRECTORY "${root}/native-assets")
get_filename_component(name "${GAME}" NAME)
file(COPY "${GAME}" DESTINATION "${root}")
file(WRITE "${root}/native-assets/runtime-index.txt"
    "# rage-rmesh-index v2\n10 model missing.rmesh missing.rmat\n")
file(WRITE "${root}/config.ini" "[video]\nrenderer=modern\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    --unset=RAGE_PORT_MODERN_ASSETS "XDG_STATE_HOME=${root}/state"
    "${root}/${name}" --config "${root}/config.ini"
    --scenario "${SOURCE}/race-scenario.ini"
    --set "disc.image=${disc}" --set run.frames=900
    --set stop.scene=12 --set stop.timer=20
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 100
    RESULT_VARIABLE result OUTPUT_FILE "${root}/stdout.log"
    ERROR_FILE "${root}/stderr.log")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Default disc source run failed: ${result}; ${root}")
endif()
file(READ "${root}/stderr.log" log)
if(NOT log MATCHES "native assets generated by C importer" OR
   log MATCHES "native asset cache " OR
   NOT log MATCHES "native GPU pipeline ready")
    message(FATAL_ERROR "Colocated cache shadowed selected disc: ${root}")
endif()
message(STATUS "Default disc source verified: ${root}")
