string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT_ROOT}/modern-features-${id}")
file(MAKE_DIRECTORY "${root}")
function(run_feature name aspect filtering post grading width expected_hash)
    set(capture "${root}/${name}.ppm")
    set(scenario "${root}/${name}.ini")
    file(WRITE "${scenario}" "[modern]\nassets = disc\n[video]\nrenderer = modern\ninternal_scale = 1\naspect = ${aspect}\nfps = logic\ntexture_filter = ${filtering}\npost = ${post}\ngrading = ${grading}\n[diagnostics]\nmodern_dump = ${capture}\nmodern_dump_scene_id = 12\nmodern_dump_timer = 120\n[race]\nenabled = true\nmode = grand-prix\nseries = gp\nclass = 0\ncourse = 0\ncar = 3\n[run]\nframes = 2500\n[stop]\nscene = 12\ntimer = 130\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
        RAGE_PORT_DISABLE_HOST_INPUT=1 RAGE_PORT_SYNC_RANDOM=12@0=1
        "${GAME}" --scenario "${scenario}" WORKING_DIRECTORY "${SOURCE}" TIMEOUT 165
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT EXISTS "${capture}")
        message(FATAL_ERROR "Modern ${name} capture failed: ${root}\n${output}${error}")
    endif()
    execute_process(COMMAND "${CHECK}" nonempty "${capture}" ${width} 240 RESULT_VARIABLE check_result)
    if(NOT check_result EQUAL 0)
        message(FATAL_ERROR "Modern ${name} capture is invalid: ${root}")
    endif()
    file(SHA256 "${capture}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Modern ${name} reference changed: ${actual_hash}")
    endif()
    set("${name}_hash" "${actual_hash}" PARENT_SCOPE)
endfunction()
run_feature(baseline auto nearest none off 320 4753f65ff72a2cb2183035d090b3cec353f174ead3ffc2a8a0e300008cc9bfd2)
run_feature(enhanced 16:9 linear fxaa vibrant 426 d0b7ccfc8d390e72d06e0f1b553ca7b1d544ff949405498ce2886309b1f4fc01)
if(baseline_hash STREQUAL enhanced_hash)
    message(FATAL_ERROR "Modern enhancement pipeline did not affect output: ${root}")
endif()
