if(NOT DEFINED FPS)
    set(FPS vsync)
endif()
if(NOT DEFINED HISTORY)
    set(HISTORY false)
endif()
if(FPS STREQUAL "logic")
    set(expected_fps 0)
elseif(FPS STREQUAL "vsync")
    set(expected_fps -1)
elseif(FPS STREQUAL "60")
    set(expected_fps 60)
else()
    message(FATAL_ERROR "FPS must be logic, vsync or 60")
endif()
set(disc "$ENV{RAGE_PORT_DISC_CUE}")
if(disc STREQUAL "")
    set(disc "${SOURCE}/disc/PAL/Rage Racer (Europe)/Rage Racer (Europe).cue")
endif()
if(NOT EXISTS "${disc}")
    message("SKIP: no disc for sampled VRAM marker")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(output "${OUTPUT_ROOT}/sampled-vram-${id}")
file(MAKE_DIRECTORY "${output}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "SDL_AUDIODRIVER=dummy" "XDG_CONFIG_HOME=${output}/config"
    "XDG_STATE_HOME=${output}/state" "RAGE_PORT_SCENARIO=1"
    "RAGE_PORT_SMOKE_FRAMES=650" "${GAME}"
    --set "disc.image=${disc}" --set video.renderer=modern
    --set "video.fps=${FPS}"
    --set race.class=1 --set race.course=0 --set diagnostics.marker_capture=true
    --set "diagnostics.marker_history=${HISTORY}" --set diagnostics.marker_frame=500
    --set diagnostics.marker_limit=1 --set diagnostics.marker_probe_x=-1
    --set diagnostics.marker_probe_y=-1
    WORKING_DIRECTORY "${SOURCE}" TIMEOUT 120
    OUTPUT_FILE "${output}/game.log" ERROR_FILE "${output}/game.log"
    RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Marker scenario failed (${result}); ${output}")
endif()
file(READ "${output}/game.log" log)
if(NOT log MATCHES "active=modern" OR log MATCHES "sampled VRAM (unavailable|save failed)")
    message(FATAL_ERROR "Missing or frame-mismatched sampled VRAM; ${output}")
endif()
file(GLOB captures "${output}/state/rage-racer/markers/*-vram-sampled.rgba")
list(LENGTH captures count)
if(NOT count EQUAL 4)
    message(FATAL_ERROR "Expected four burst captures, got ${count}; ${output}")
endif()
foreach(capture IN LISTS captures)
    file(SIZE "${capture}" bytes)
    if(NOT bytes EQUAL 2097152)
        message(FATAL_ERROR "Incomplete 1024x512 RGBA capture: ${capture}")
    endif()
    string(REPLACE "-vram-sampled.rgba" "-info.txt" info_path "${capture}")
    file(READ "${info_path}" info)
    if(NOT info MATCHES "^frame=([0-9]+) ")
        message(FATAL_ERROR "Missing scene frame in ${info_path}")
    endif()
    set(scene_frame "${CMAKE_MATCH_1}")
    if(NOT info MATCHES "sampledVram frame=([0-9]+) matchesScene=1 ")
        message(FATAL_ERROR "Sampled texture does not match scene in ${info_path}")
    endif()
    if(NOT CMAKE_MATCH_1 STREQUAL scene_frame)
        message(FATAL_ERROR "Scene and sampled texture have different frames in ${info_path}")
    endif()
    if(NOT info MATCHES "modernImage=1 " OR NOT info MATCHES " fps=${expected_fps}[\r\n]")
        message(FATAL_ERROR "Wrong presentation mode or absent modern image in ${info_path}")
    endif()
endforeach()
if(HISTORY)
    if(log MATCHES "cannot (save retained|retain render world)")
        message(FATAL_ERROR "Retained bank write failed; ${output}")
    endif()
    file(GLOB banks "${output}/state/rage-racer/markers/ring-*-g*-bank*.raw")
    list(LENGTH banks bank_count)
    if(NOT bank_count EQUAL 48)
        message(FATAL_ERROR "Expected 16 history entries with three banks, got ${bank_count}; ${output}")
    endif()
    foreach(bank IN LISTS banks)
        file(SIZE "${bank}" bytes)
        if(NOT bytes EQUAL 1048576)
            message(FATAL_ERROR "Incomplete retained bank: ${bank}")
        endif()
        get_filename_component(name "${bank}" NAME)
        if(NOT name MATCHES "^(ring-[0-9]+-f[0-9]+)-g([0-9]+)-bank(-1|0|1)\\.raw$")
            message(FATAL_ERROR "Invalid retained bank identity: ${bank}")
        endif()
        set(frame_prefix "${CMAKE_MATCH_1}")
        set(generation "${CMAKE_MATCH_2}")
        set(bank_id "${CMAKE_MATCH_3}")
        set(scene "${output}/state/rage-racer/markers/${frame_prefix}-scene.bin")
        if(NOT EXISTS "${scene}")
            message(FATAL_ERROR "Retained bank lacks its captured scene: ${bank}")
        endif()
        if(NOT EXISTS "${output}/state/rage-racer/markers/${frame_prefix}-world.bin")
            message(FATAL_ERROR "History entry lacks its retained render world: ${bank}")
        endif()
        foreach(expected_bank -1 0 1)
            if(NOT EXISTS "${output}/state/rage-racer/markers/${frame_prefix}-g${generation}-bank${expected_bank}.raw")
                message(FATAL_ERROR "Incomplete bank set for ${frame_prefix}")
            endif()
        endforeach()
        file(SHA256 "${bank}" digest)
        set(identity "digest_g${generation}_bank${bank_id}")
        if(DEFINED ${identity} AND NOT "${${identity}}" STREQUAL digest)
            message(FATAL_ERROR "Pixels changed within retained generation ${generation}, bank ${bank_id}")
        endif()
        set(${identity} "${digest}")
    endforeach()
endif()
message(STATUS "Four submitted-frame VRAM captures verified (fps=${FPS}); ${output}")
