set(assets "$ENV{RAGE_PORT_NATIVE_ASSETS}")
if(NOT EXISTS "${assets}/runtime-index.txt")
    set(assets "${SOURCE}/build/release/native-assets")
endif()
if(NOT EXISTS "${assets}/runtime-index.txt")
    message("SKIP: no imported assets")
    return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(work "${OUTPUT_ROOT}/stage-angles-${id}")
file(MAKE_DIRECTORY "${work}")
function(render name)
    execute_process(COMMAND "${TOOL}" --assets "${assets}" --width 240 --height 180
        --output "${work}/${name}.ppm" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 600)
    file(WRITE "${work}/${name}.log" "${output}${error}")
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Stage render ${name} failed (${result}): ${work}/${name}.log")
    endif()
endfunction()
function(check mode)
    execute_process(COMMAND "${CHECK}" "${mode}" ${ARGN} RESULT_VARIABLE result)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Stage ${mode} invariant failed: ${work}")
    endif()
endfunction()
function(sweep_paths out name count)
    math(EXPR last "${count} - 1")
    set(paths)
    foreach(step RANGE 0 ${last})
        if(step LESS 10)
            set(padded "00${step}")
        else()
            set(padded "0${step}")
        endif()
        list(APPEND paths "${work}/${name}-${padded}.ppm")
    endforeach()
    set(${out} "${paths}" PARENT_SCOPE)
endfunction()
foreach(key 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44)
    render(car${key} --pose model:${key}:0 --quat --elevation 20 --sweep 24)
    sweep_paths(paths car${key} 24)
    check(sweep ${paths})
endforeach()
foreach(angle "0,37,0" "0,123,0" "0,250,0" "20,37,15" "-35,110,25")
    render(euler${angle} --pose model:10:0 --rot "${angle}" --elevation 20)
    render(quat${angle} --pose model:10:0 --rot "${angle}" --elevation 20 --quat)
    check(rotation "${work}/euler${angle}.ppm" "${work}/quat${angle}.ppm")
endforeach()
render(turn0 --pose model:10:0 --elevation 20 --rot 0,0,0)
render(resized --pose model:10:0 --elevation 20 --rot 0,0,0 --prime-aspect 0.5)
check(equal "${work}/turn0.ppm" "${work}/resized.ppm")
render(reloaded --pose model:10:0 --elevation 20 --rot 0,0,0 --reload-assets)
check(equal "${work}/turn0.ppm" "${work}/reloaded.ppm")
render(turn360 --pose model:10:0 --elevation 20 --rot 0,360,0)
check(equal "${work}/turn0.ppm" "${work}/turn360.ppm")
render(again1 --pose model:10:0 --elevation 20 --sweep 4)
render(again2 --pose model:10:0 --elevation 20 --sweep 4)
sweep_paths(first again1 4)
sweep_paths(second again2 4)
foreach(i RANGE 0 3)
    list(GET first ${i} a)
    list(GET second ${i} b)
    check(equal "${a}" "${b}")
endforeach()
foreach(set course terrain track1 track2)
    render(${set} --pose ${set}:88:0 --elevation 30)
    check(track "${work}/${set}.ppm")
endforeach()
message(STATUS "Compiled stage angles passed: ${work}")
