string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(root "${OUTPUT_ROOT}/native-world-${id}")
file(MAKE_DIRECTORY "${root}/mod/textures")
execute_process(COMMAND "${FIXTURE}" "${root}" RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native fixture generation failed: ${root}")
endif()
file(RENAME "${root}/terrain.png" "${root}/mod/textures/terrain.png")
file(WRITE "${root}/mod/mod.toml" "[mod]\nid = \"native-world-test\"\n[textures]\n\"track.big1.terrain.material.0\" = \"textures/terrain.png\"\n")
file(WRITE "${root}/scenario.ini" "[video]\nrenderer=modern\n[race]\nenabled=true\nmode=grand-prix\nclass=0\ncourse=0\ncar=3\n[run]\nframes=900\n[stop]\nscene=12\ntimer=20\n")
function(run name)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
        "RAGE_PORT_MODERN_ASSETS=${root}" RAGE_PORT_MODERN_ASSET_TRACE=1
        "RAGE_PORT_MODS_DIRECTORY=${root}/mod" "${GAME}" ${ARGN}
        WORKING_DIRECTORY "${SOURCE}" TIMEOUT 105 RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(log "${output}${error}")
    file(WRITE "${root}/${name}.log" "${log}")
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "${name} failed (${result}): ${root}")
    endif()
    set(log "${log}" PARENT_SCOPE)
endfunction()
function(require pattern)
    if(NOT log MATCHES "${pattern}")
        message(FATAL_ERROR "Missing ${pattern}: ${root}")
    endif()
endfunction()
run(race --scenario "${root}/scenario.ini" --set diagnostics.performance_trace=true)
require("native-geometry-prepare frame=[0-9]+ instances=[1-9][0-9]* main_vertices=[1-9][0-9]* mirror_vertices=[0-9]+ snapshot_ms=[0-9]+[.][0-9]+ warm_ms=[0-9]+[.][0-9]+ shadow_setup_ms=[0-9]+[.][0-9]+ main_ms=[0-9]+[.][0-9]+ mirror_ms=[0-9]+[.][0-9]+ completeness_ms=[0-9]+[.][0-9]+")
require("native GPU pipeline ready")
require("semantic asset mod native-world-test")
require("native texture override track[.]big1[.]terrain[.]material[.]0 <- textures/terrain[.]png \\(64x32\\)")
require("native car paint asset=")
require("native world frame=[0-9]+ camera=[1-9][0-9]* instances=[1-9][0-9]* cached=[1-9][0-9]* textures=[0-9]+ vertices=[1-9][0-9]* spans=[1-9][0-9]*")
require("native draws frame=[0-9]+ draws=[1-9][0-9]* vertices=[1-9][0-9]*")
run(attract --set video.renderer=modern --set race.enabled=false --set boot.direct=false
    --set run.frames=2500 --set stop.scene=30 --set stop.timer=200)
require("scene=30 timer=200")
require("native shadow map frame=[0-9]+ draws=[1-9][0-9]* masked=[1-9][0-9]*")
message(STATUS "Native world compiled fixture passed: ${root}")
