#ifndef GAME_FRONTEND_TYPES_H
#define GAME_FRONTEND_TYPES_H

typedef enum FrontendState {
    FRONTEND_STATE_INVALID = -1,
    FRONTEND_STATE_TITLE,
    FRONTEND_STATE_MENU_OPENING,
    FRONTEND_STATE_MENU_INPUT,
    FRONTEND_STATE_MENU_EXIT
} FrontendState;

#endif
