#ifndef GAME_SCENE_H
#define GAME_SCENE_H

/* Top-level scene dispatch slots. Entry scenes perform one-time setup and
 * normally replace themselves with the following update scene. */
typedef enum GameSceneId {
    GAME_SCENE_BOOT_LOGO = 1,
    GAME_SCENE_ENTER_FRONTEND = 2,
    GAME_SCENE_ENTER_TITLE = 3,
    GAME_SCENE_FRONTEND = 4,
    GAME_SCENE_FMV = 5,
    GAME_SCENE_INIT_MENU = 6,
    GAME_SCENE_RETURN_FROM_CLASS_FMV = 7,
    GAME_SCENE_MENU = 8,
    GAME_SCENE_ENTER_ROUND = 9,
    GAME_SCENE_ROUND = 10,
    GAME_SCENE_ENTER_RACE = 11,
    GAME_SCENE_RACE = 12,
    GAME_SCENE_ENTER_LOST_RACE = 13,
    GAME_SCENE_LOST_RACE = 14,
    GAME_SCENE_ENTER_RACE_END = 15,
    GAME_SCENE_RACE_END = 16,
    GAME_SCENE_REPLAY = 17,
    GAME_SCENE_ENTER_PRIZE = 18,
    GAME_SCENE_PRIZE = 19,
    GAME_SCENE_ENTER_RECORD_ENTRY = 20,
    GAME_SCENE_RECORD_ENTRY = 21,
    GAME_SCENE_ENTER_ATTRACT = 22,
    GAME_SCENE_OPTION = 23,
    GAME_SCENE_ENTER_MEMORY_CARD = 24,
    GAME_SCENE_ENTER_MEMORY_CARD_LOAD = 25,
    GAME_SCENE_MEMORY_CARD = 26,
    GAME_SCENE_ENTER_BGM_SELECT = 27,
    GAME_SCENE_BGM_SELECT = 28,
    GAME_SCENE_ENTER_ATTRACT_DEMO = 29,
    GAME_SCENE_ATTRACT_DEMO = 30,
    GAME_SCENE_ENTER_PROLOGUE = 31,
    GAME_SCENE_PROLOGUE = 32,
    GAME_SCENE_RETURN_FROM_ENDING_FMV = 33,
    GAME_SCENE_ENDING_STILL = 34,
} GameSceneId;

#endif
