#include "modern_shader_sources.h"

const char MODERN_SHADER_MSL[] =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct VSIn {\n"
    "    float4 pos [[attribute(0)]];\n"
    "    float2 uv [[attribute(1)]];\n"
    "    uchar4 color [[attribute(2)]];\n"
    "    uint attr [[attribute(3)]];\n"
    "    uint twin [[attribute(4)]];\n"
    "    uint clut [[attribute(5)]];\n"
    "};\n"
    "struct VSOut {\n"
    "    float4 pos [[position]];\n"
    "    float4 color;\n"
    "    float2 uv;\n"
    "    uint attr [[flat]];\n"
    "    uint twin [[flat]];\n"
    "    uint clut [[flat]];\n"
    "};\n"
    "vertex VSOut vs_main(VSIn in [[stage_in]]) {\n"
    "    VSOut out;\n"
    "    out.pos = in.pos;\n"
    "    out.color = float4(in.color) / 255.0;\n"
    "    out.uv = in.uv;\n"
    "    out.attr = in.attr;\n"
    "    out.twin = in.twin;\n"
    "    out.clut = in.clut;\n"
    "    return out;\n"
    "}\n"
    "static uint rgb5551(float4 c) {\n"
    "    uint r = uint(c.r * 31.0 + 0.5);\n"
    "    uint g = uint(c.g * 31.0 + 0.5);\n"
    "    uint b = uint(c.b * 31.0 + 0.5);\n"
    "    uint a = uint(c.a + 0.5);\n"
    "    return r | (g << 5) | (b << 10) | (a << 15);\n"
    "}\n"
    "static float4 texelLookup(texture2d<float> vram, uint2 pageBase,\n"
    "                          uint2 texel, uint mode, uint clut) {\n"
    "    if (mode >= 2u) {\n"
    "        return vram.read(pageBase + texel);\n"
    "    }\n"
    "    uint texelShift = (mode == 1u) ? 1u : 2u;\n"
    "    uint subMask = (mode == 1u) ? 1u : 3u;\n"
    "    uint idxShift = (mode == 1u) ? 8u : 4u;\n"
    "    uint idxMask = (mode == 1u) ? 0xFFu : 0xFu;\n"
    "    uint sub = texel.x & subMask;\n"
    "    uint2 pos = uint2(texel.x >> texelShift, texel.y);\n"
    "    uint word16 = rgb5551(vram.read(pageBase + pos));\n"
    "    uint colorIdx = (word16 >> (sub * idxShift)) & idxMask;\n"
    "    uint2 clutBase = uint2((clut % 64u) * 16u, clut / 64u);\n"
    "    return vram.read(clutBase + uint2(colorIdx, 0u));\n"
    "}\n"
    "fragment float4 fs_main(VSOut in [[stage_in]],\n"
    "                        texture2d<float> vram [[texture(0)]],\n"
    "                        sampler smp [[sampler(0)]]) {\n"
    "    uint texWord = in.attr;\n"
    "    uint tpage = texWord & 0x1FFu;\n"
    "    bool untextured = (texWord & 0x8000u) != 0u;\n"
    "    bool filterTex = (texWord & 0x10000u) != 0u;\n"
    "    float4 texColor;\n"
    "    if (untextured) {\n"
    "        texColor = float4(1.0, 1.0, 1.0, 2.0);\n"
    "    } else {\n"
    "        uint2 twAnd = uint2(in.twin & 0xFFu, (in.twin >> 8) & 0xFFu);\n"
    "        uint2 twOr = uint2((in.twin >> 16) & 0xFFu,\n"
    "                           (in.twin >> 24) & 0xFFu);\n"
    "        uint2 pageBase = uint2(((tpage % 32u) % 16u) * 64u,\n"
    "                               ((tpage % 32u) / 16u) * 256u);\n"
    "        uint mode = (tpage >> 7) & 3u;\n"
    "        float2 fuv = clamp(floor(in.uv + float2(1.0 / 131072.0)),\n"
    "                           0.0, 255.0);\n"
    "        uint2 texel = (uint2(fuv) & twAnd) | twOr;\n"
    "        texColor = texelLookup(vram, pageBase, texel, mode, in.clut);\n"
    "        /* The nearest texel keeps the transparency-key and semi bits:\n"
    "         * cutout silhouettes stay pixel-identical to compat, only the\n"
    "         * interior colour is smoothed. Transparent-key neighbours drop\n"
    "         * out of the blend so they never bleed black into edges. */\n"
    "        if (all(texColor == float4(0.0))) {\n"
    "            discard_fragment();\n"
    "        }\n"
    "        if (filterTex) {\n"
    "            float2 pos = in.uv + float2(1.0 / 131072.0) - 0.5;\n"
    "            float2 cell = floor(pos);\n"
    "            float2 frac = pos - cell;\n"
    "            float3 acc = float3(0.0);\n"
    "            float weightSum = 0.0;\n"
    "            for (int tap = 0; tap < 4; tap++) {\n"
    "                float2 offset = float2(float(tap & 1), float(tap >> 1));\n"
    "                float2 at = clamp(cell + offset, 0.0, 255.0);\n"
    "                float2 axis = abs(offset - frac);\n"
    "                float weight = (1.0 - axis.x) * (1.0 - axis.y);\n"
    "                uint2 t = (uint2(at) & twAnd) | twOr;\n"
    "                float4 c = texelLookup(vram, pageBase, t, mode,\n"
    "                                       in.clut);\n"
    "                if (!all(c == float4(0.0))) {\n"
    "                    acc += c.rgb * weight;\n"
    "                    weightSum += weight;\n"
    "                }\n"
    "            }\n"
    "            if (weightSum > 0.0) {\n"
    "                texColor = float4(acc / weightSum, texColor.a);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    bool semiPrim = in.color.a < 0.75;\n"
    "    bool texelSemi = texColor.a > 0.0;\n"
    "    float3 modColor;\n"
    "    if (untextured) {\n"
    "        modColor = in.color.rgb;\n"
    "    } else {\n"
    "        float3 tex5 = filterTex ? texColor.rgb * 31.0\n"
    "                                : floor(texColor.rgb * 31.0 + 0.5);\n"
    "        float3 col8 = min(floor(in.color.rgb * 255.0 + 0.5),\n"
    "                          float3(255.0));\n"
    "        float3 prod8 = min(tex5 * col8 / 16.0, float3(255.0));\n"
    "        modColor = prod8 / 255.0;\n"
    "    }\n"
    "    if (texelSemi && semiPrim) {\n"
    "        uint abr = (tpage & 0x60u) >> 5u;\n"
    "        if (abr == 0u) {\n"
    "            return float4(modColor * 0.5, 0.5);\n"
    "        } else if (abr == 3u) {\n"
    "            return float4(modColor * 0.25, 0.0);\n"
    "        }\n"
    "        return float4(modColor, 0.0);\n"
    "    }\n"
    "    return float4(modColor, 1.0);\n"
    "}\n";

/* Post-processing: a fullscreen pass over the finished frame. One built-in
 * effect for now (FXAA edge anti-aliasing); the pass is the extension point
 * for further effects. */
const char MODERN_POST_MSL[] =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct PostOut { float4 pos [[position]]; float2 uv; };\n"
    "vertex PostOut vs_post(uint vid [[vertex_id]]) {\n"
    "    PostOut out;\n"
    "    float2 corner = float2((vid << 1) & 2, vid & 2);\n"
    "    out.pos = float4(corner * 2.0 - 1.0, 0.0, 1.0);\n"
    "    out.uv = float2(corner.x, 1.0 - corner.y);\n"
    "    return out;\n"
    "}\n"
    "static float fxaaLuma(float3 c) {\n"
    "    return dot(c, float3(0.299, 0.587, 0.114));\n"
    "}\n"
    "fragment float4 fs_post(PostOut in [[stage_in]],\n"
    "                        texture2d<float> frame [[texture(0)]],\n"
    "                        sampler smp [[sampler(0)]]) {\n"
    "    float2 texel = 1.0 / float2(frame.get_width(), frame.get_height());\n"
    "    float3 rgbNW = frame.sample(smp, in.uv + float2(-1, -1) * texel).rgb;\n"
    "    float3 rgbNE = frame.sample(smp, in.uv + float2(1, -1) * texel).rgb;\n"
    "    float3 rgbSW = frame.sample(smp, in.uv + float2(-1, 1) * texel).rgb;\n"
    "    float3 rgbSE = frame.sample(smp, in.uv + float2(1, 1) * texel).rgb;\n"
    "    float4 center = frame.sample(smp, in.uv);\n"
    "    float lumaNW = fxaaLuma(rgbNW), lumaNE = fxaaLuma(rgbNE);\n"
    "    float lumaSW = fxaaLuma(rgbSW), lumaSE = fxaaLuma(rgbSE);\n"
    "    float lumaM = fxaaLuma(center.rgb);\n"
    "    float lumaMin = min(lumaM, min(min(lumaNW, lumaNE),\n"
    "                                   min(lumaSW, lumaSE)));\n"
    "    float lumaMax = max(lumaM, max(max(lumaNW, lumaNE),\n"
    "                                   max(lumaSW, lumaSE)));\n"
    "    float2 dir = float2(-((lumaNW + lumaNE) - (lumaSW + lumaSE)),\n"
    "                        (lumaNW + lumaSW) - (lumaNE + lumaSE));\n"
    "    float dirReduce = max((lumaNW + lumaNE + lumaSW + lumaSE) *\n"
    "                              0.25 * (1.0 / 8.0),\n"
    "                          1.0 / 128.0);\n"
    "    float rcpDirMin = 1.0 / (min(abs(dir.x), abs(dir.y)) + dirReduce);\n"
    "    dir = clamp(dir * rcpDirMin, float2(-8.0), float2(8.0)) * texel;\n"
    "    float3 rgbA = 0.5 *\n"
    "        (frame.sample(smp, in.uv + dir * (1.0 / 3.0 - 0.5)).rgb +\n"
    "         frame.sample(smp, in.uv + dir * (2.0 / 3.0 - 0.5)).rgb);\n"
    "    float3 rgbB = rgbA * 0.5 + 0.25 *\n"
    "        (frame.sample(smp, in.uv + dir * -0.5).rgb +\n"
    "         frame.sample(smp, in.uv + dir * 0.5).rgb);\n"
    "    float lumaB = fxaaLuma(rgbB);\n"
    "    float3 result = (lumaB < lumaMin || lumaB > lumaMax) ? rgbA : rgbB;\n"
    "    return float4(result, center.a);\n"
    "}\n";

/* Highlight glow and colour grading. The bright pass extracts highlights
 * into a quarter-resolution target, two separable Gaussian passes blur
 * them, and the composite pass screen-blends the glow over the frame and
 * optionally applies a vibrance/contrast grade. The composite shader is
 * generated with its config baked in as constants. */
const char MODERN_EFFECTS_MSL[] =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct PostOut { float4 pos [[position]]; float2 uv; };\n"
    "vertex PostOut vs_fx(uint vid [[vertex_id]]) {\n"
    "    PostOut out;\n"
    "    float2 corner = float2((vid << 1) & 2, vid & 2);\n"
    "    out.pos = float4(corner * 2.0 - 1.0, 0.0, 1.0);\n"
    "    out.uv = float2(corner.x, 1.0 - corner.y);\n"
    "    return out;\n"
    "}\n"
    "fragment float4 fs_bright(PostOut in [[stage_in]],\n"
    "                          texture2d<float> frame [[texture(0)]],\n"
    "                          sampler smp [[sampler(0)]]) {\n"
    "    float3 c = frame.sample(smp, in.uv).rgb;\n"
    "    float luma = dot(c, float3(0.299, 0.587, 0.114));\n"
    "    return float4(c * smoothstep(0.55, 0.9, luma), 1.0);\n"
    "}\n"
    "static float4 blurPass(PostOut in, texture2d<float> frame, sampler smp,\n"
    "                       float2 dir) {\n"
    "    float2 texel = dir / float2(frame.get_width(), frame.get_height());\n"
    "    const float w[5] = {0.227027, 0.1945946, 0.1216216, 0.054054,\n"
    "                        0.016216};\n"
    "    float3 acc = frame.sample(smp, in.uv).rgb * w[0];\n"
    "    for (int i = 1; i < 5; i++) {\n"
    "        acc += frame.sample(smp, in.uv + texel * float(i)).rgb * w[i];\n"
    "        acc += frame.sample(smp, in.uv - texel * float(i)).rgb * w[i];\n"
    "    }\n"
    "    return float4(acc, 1.0);\n"
    "}\n"
    "fragment float4 fs_blur_h(PostOut in [[stage_in]],\n"
    "                          texture2d<float> frame [[texture(0)]],\n"
    "                          sampler smp [[sampler(0)]]) {\n"
    "    return blurPass(in, frame, smp, float2(1.0, 0.0));\n"
    "}\n"
    "fragment float4 fs_blur_v(PostOut in [[stage_in]],\n"
    "                          texture2d<float> frame [[texture(0)]],\n"
    "                          sampler smp [[sampler(0)]]) {\n"
    "    return blurPass(in, frame, smp, float2(0.0, 1.0));\n"
    "}\n";

/* Composite prologue + body; the generated "constant float kBloom = ...;
 * constant int kGrading = ...;" lines are inserted between them. */
const char MODERN_COMPOSITE_PROLOGUE_MSL[] =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n";
const char MODERN_COMPOSITE_MSL[] =
    "struct PostOut { float4 pos [[position]]; float2 uv; };\n"
    "fragment float4 fs_composite(PostOut in [[stage_in]],\n"
    "                             texture2d<float> frame [[texture(0)]],\n"
    "                             sampler smpFrame [[sampler(0)]],\n"
    "                             texture2d<float> bloom [[texture(1)]],\n"
    "                             sampler smpBloom [[sampler(1)]]) {\n"
    "    float3 c = frame.sample(smpFrame, in.uv).rgb;\n"
    "    if (kBloom > 0.0) {\n"
    "        float3 b = saturate(bloom.sample(smpBloom, in.uv).rgb * kBloom);\n"
    "        c = 1.0 - (1.0 - saturate(c)) * (1.0 - b);\n"
    "    }\n"
    "    if (kGrading != 0) {\n"
    "        float luma = dot(c, float3(0.299, 0.587, 0.114));\n"
    "        c = mix(float3(luma), c, 1.16);\n"
    "        c = (c - 0.5) * 1.04 + 0.5;\n"
    "    }\n"
    "    return float4(saturate(c), 1.0);\n"
    "}\n";

const size_t MODERN_SHADER_MSL_SIZE = sizeof(MODERN_SHADER_MSL);
const size_t MODERN_POST_MSL_SIZE = sizeof(MODERN_POST_MSL);
const size_t MODERN_EFFECTS_MSL_SIZE = sizeof(MODERN_EFFECTS_MSL);
const size_t MODERN_COMPOSITE_PROLOGUE_MSL_SIZE = sizeof(MODERN_COMPOSITE_PROLOGUE_MSL);
const size_t MODERN_COMPOSITE_MSL_SIZE = sizeof(MODERN_COMPOSITE_MSL);
