function(rage_verify_route_completion log completion races)
    if(log MATCHES "incomplete native world")
        message(FATAL_ERROR "Route completed with incomplete native geometry")
    endif()
    if(NOT log MATCHES "autopilot result=complete ${completion}[\r\n]" OR
       log MATCHES "autopilot result=failed")
        message(FATAL_ERROR "Missing exact successful route completion: ${completion}")
    endif()
    if(races GREATER 1)
        string(REGEX MATCHALL "scenario repeat entered next race via menus" repeats "${log}")
        list(LENGTH repeats repeat_count)
        math(EXPR expected_repeats "${races} - 1")
        if(NOT repeat_count EQUAL expected_repeats)
            message(FATAL_ERROR "Expected ${expected_repeats} menu-driven repeat transitions, got ${repeat_count}")
        endif()
    endif()
endfunction()
